### ISSUE TITLE
Instanced Meshes can't use the same edgeRenderer

### ISSUE THREAD

**Issue by Ian19** [BabylonJS/Babylon.js#6539] opened 2019-06-27 06:06 UTC
If a scene contains instances of a mesh that all use an edgeRenderer then **multiple identical lineShader materials are created** for each instance. It might be efficient if mesh instances could all use one instance of lineShader or edgeRenderer.

[forum](https://forum.babylonjs.com/t/instancing-question-can-multiple-meshes-use-the-same-edgesrenderer/4153)

Maybe code like this:

box2.edgesRenderer = box1.edgesRenderer;

[Playground](https://www.babylonjs-playground.com/#TAZ2CB#51)

Thanks in advance.

**Comment by sebavan** [comment] 2019-06-27 12:58
This would only be possible for instances where only one draw call could potentially render all the edges.

**Comment by Popov72** [comment] 2020-05-26 07:34
I'm not sure it can be done for instances...

Everything instance related is done at the sub mesh level (notably the list of visible instances), whereas the edge renderer works at the mesh geometry level: it is using the vertex buffer to create the lines, irrelevant of the sub meshes structure of the mesh.

So, that would mean creating in the edge renderer a set of lines for each different sub mesh, and in the render method we should loop over the sub meshes and issue a draw call for each. The problem is that we don't know which sub meshes are visible or not in this frame. Also, we don't have the world0/.../world3 vertex buffers set correctly (the current values are the ones set to draw the last drawn sub mesh), so we have to update them before each draw call.

Should we still do it? If yes, it still remain the problem to know which sub-meshes of the mesh are visible in the current frame.

Note however that thin instances can be supported easily in the edge renderer (I have already performed the changes in my local repo).

**Comment by Popov72** [comment] 2020-05-26 07:38
Regarding the op problem:
> multiple identical lineShader materials are created for each instance

We could create the `lineShader` a single time and keep it as a static property of the class.

**Comment by Popov72** [comment] 2020-05-26 07:57
Easier to discuss with some code: #8265

**Comment by sebavan** [comment] 2020-05-26 13:05
Love the idea and understand the issue, go for it, it will already saves the state change associated to the program which costs a lot :-)

We ll close this as soon as the PR goes in. Thanks a lot.

**Comment by sebavan** [comment] 2020-05-26 16:41
Thanks to @Popov72 all done !!!

**Closed by sebavan** 2020-05-26 16:41 UTC
Labels: enhancement, help wanted, rendering engine

**Comment by Ian19** [comment] 2020-05-27 01:55
Thanks Popov72!
