### ISSUE TITLE
New glTF model AttentuationTest not rendering properly

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Babylon.js#10380] opened 2021-05-17 16:28 UTC
**Repro**
- Bug repro: https://sandbox.babylonjs.com/?assetUrl=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/attenuation-test/2.0/AttenuationTest/glTF/AttenuationTest.gltf

- Expected result: See screenshot https://github.com/KhronosGroup/glTF-Sample-Models/tree/attenuation-test/2.0/AttenuationTest#readme
![image](https://user-images.githubusercontent.com/19158740/118523432-fba1f180-b6f1-11eb-8183-0241cc21431d.png)

- Current result: The node scale row looks different than the screenshot
![image](https://user-images.githubusercontent.com/19158740/118523597-22f8be80-b6f2-11eb-9a3a-6f174b0435a2.png)

**Comment by emackey** [comment] 2021-05-17 17:43
PR for the sample model is open now:  https://github.com/KhronosGroup/glTF-Sample-Models/pull/314

The failure on the "node scale" row came as a surprise to me, as this bug was already addressed in #10151.  I'm not sure why that fix doesn't apply here.  One thing that's different is that this model uses the same material on multiple, differently-scaled nodes, unlike the test model from #10151.

**Comment by Popov72** [comment] 2021-05-17 22:23
The problem is that when multiple gltf nodes are pointing to the same mesh, we use instancing for those meshes. It means they all are rendered in a single draw call and the world scale used to modulate the thickness is the one from the master mesh (the first mesh we encounter in the file). Here, all the meshes of the "Node Scale" line are instances of the 3rd mesh of the "Thickness Factor" line and the world scales we use are the ones from this mesh.

If I disable usage of instancing it does work:
![image](https://user-images.githubusercontent.com/4152247/118563532-05b60580-b76f-11eb-8857-33761289f1b6.png)

@bghgary I don't really know how to fix that... We could try to disable instancing for meshes that use materials that are using the `KHR_materials_volume` extension but I think we don't have this info at the right time when parsing the file to be able to disable instancing(?)

**Comment by bghgary** [comment] 2021-05-17 22:31
> I don't really know how to fix that... We could try to disable instancing for meshes that use materials that are using the KHR_materials_volume extension but I think we don't have this info at the right time when parsing the file to be able to disable instancing(?)

Yeah, this is going to be a bit tricky. I wonder if we can completely disable instancing for the whole glTF if KHR_materials_volume is in `extensionsUsed`?

**Comment by Popov72** [comment] 2021-05-17 22:38
That's what I thought was the easiest to do.

**Comment by Popov72** [comment] 2021-05-17 22:46
Is the best way to do it in the GLTFLoader._loadExtensions function:
```typescript
private _loadExtensions(): void {
    for (const name in GLTFLoader._RegisteredExtensions) {
        const extension = GLTFLoader._RegisteredExtensions[name].factory(this);
        if (extension.name !== name) {
            Logger.Warn(`The name of the glTF loader extension instance does not match the registered name: ${extension.name} !== ${name}`);
        }

        this._extensions.push(extension);
        this._parent.onExtensionLoadedObservable.notifyObservers(extension);

        if (extension.name === "KHR_materials_volume") {
            this._parent.createInstances = false;
        }
    }

    this._extensions.sort((a, b) => (a.order || Number.MAX_VALUE) - (b.order || Number.MAX_VALUE));
    this._parent.onExtensionLoadedObservable.clear();
}
```
?

**Comment by Popov72** [comment] 2021-05-17 22:53
Tentative PR: #10383

**Comment by bghgary** [comment] 2021-05-17 23:07
The extension itself should be able to set the parent's flag.

**Comment by bghgary** [comment] 2021-05-17 23:09
Something like this:

https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/2.0/Extensions/KHR_materials_volume.ts#L44
```typescript
        if (this.enabled) {
            this._loader.parent.createInstances = false;
        }
```

**Closed** 2021-05-18 15:04 UTC
Labels: glTF, rendering engine
