### ISSUE TITLE
BabylonjsGUI npm package using Webpack

### ISSUE THREAD

**Issue by massile** [BabylonJS/Babylon.js#2848] opened 2017-09-21 18:39 UTC
I have a project with `babylonjs` and `babylonjs-gui` packages installed (3.1.2 alpha2 and 3.1.0-alpha1.3 respectively).
Everything is fine if I only have babylonjs imported.
However, if I import `babylonjs-gui`, I have this error:

```
babylon.gui.js:7 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (babylon.gui.js:7)
    at babylon.gui.js:17
    at BABYLON.GUI.BABYLON.GUI (babylon.gui.js:346)
    at BABYLON (babylon.gui.js:348)
    at Object.<anonymous> (babylon.gui.js:349)
    at __webpack_require__ (bootstrap 25fc1da1156af93de89b:19)
    at Object.<anonymous> (process.js:106)
    at __webpack_require__ (bootstrap 25fc1da1156af93de89b:19)
    at Object.setPrototypeOf.__proto__ (index.js:43)
```

the js file:

```js
import * as BABYLON from 'babylonjs';
import * as GUI from 'babylonjs-gui'; // Pops the error
```

**Comment by deltakosh** [comment] 2017-09-21 18:41
Duplicate of #2569

**Comment by deltakosh** [comment] 2017-09-21 18:41
It will be fixed today or tomorrow

**Closed by deltakosh** 2017-09-21 18:41 UTC

**Comment by massile** [comment] 2017-09-21 18:43
Nice ! Thanks
