### ISSUE TITLE
GUI TextBlock with percentage font size appears misaligned when render canvas is small

### ISSUE THREAD

**Issue by nbduke** [BabylonJS/Babylon.js#8875] opened 2020-09-04 19:24 UTC
Repro playground: https://www.babylonjs-playground.com/#XTHWYN#3

The above playground creates a plane with a very simple texture GUI. If I give the `TextBlock` in the simple button a percentage font size (e.g. 40%), then when I load the playground in a small window (i.e. the render canvas is small), it renders off-center. However, if I switch to an absolute size (e.g. 400px), this doesn't happen.

![image](https://user-images.githubusercontent.com/38300641/92278199-8f57c880-eea9-11ea-8bc1-97c2718b3602.png)

Maybe this isn't a bug, but percentage font sizes are nice because they make UI more flexible to being rendered on different sized meshes. It doesn't *seem* like the position of the text should be affected by the size of the canvas.

**Comment by sebavan** [comment] 2020-09-04 20:45
@nbduke thanks for the repro, we ll look into it ASAP so I guess on Monday to ensure you ll have your answer after labor day :-)

**Comment by Popov72** [comment] 2020-09-06 17:25
I can't reproduce your problem:
![image](https://user-images.githubusercontent.com/4152247/92331397-8831e580-f076-11ea-847c-58c1e3b7999c.png)

**Comment by sebavan** [comment] 2020-09-06 17:39
I had to open the tab real small before running the code :-) if that helps ?

**Comment by sebavan** [comment] 2020-09-06 17:40
wonder if the resize is not listened somewhere, but could not find where :-(

**Comment by Popov72** [comment] 2020-09-06 19:11
![image](https://user-images.githubusercontent.com/4152247/92333391-60964980-f085-11ea-95b5-8df9392e08f7.png)
Still not able to reproduce the problem...

**Comment by nbduke** [comment] 2020-09-06 22:56
My exact steps are:
1. Open Chrome
2. Resize the window to be very small
3. Navigate to the Playground

It doesn't seem to repro if I load the Playground in a large window then resize to small.

**Comment by Popov72** [comment] 2020-09-07 15:02
Thanks for the repro!

Fixed by #8893

**Closed** 2020-09-07 15:45 UTC
Labels: bug, investigation
