### ISSUE TITLE
Get rid of *.module.d.ts and update docs

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#2843] opened 2017-09-21 15:44 UTC

**Comment by zakhenry** [comment] 2017-09-25 17:10
In this can you please also look into the regression with import behavior?

I use the spread pattern of `import { Vector3, Scene } from 'babylonjs` pattern extensively, and the latest update to split out modules has made the variables become untyped. For this reason I'm not willing to make the jump to alpha3.5 :(

It looks like using `import * as BABYLON from 'babylonjs` works fine with types, but this is a bit painful to add as prefixing all members with `BABYLON.` doesn't fit with our code style guidelines.

Additionally, the spread technique should be encouraged, as it allows for the api to be safely fragmented into separate files allow for tools like webpack to do efficient tree shaking etc

**Comment by RaananW** [comment] 2017-09-26 08:06
Hi @zakhenry ,

The spread operator should be working fine:

![image](https://user-images.githubusercontent.com/1381702/30849181-c7bff398-a2a1-11e7-8b3b-d7c4d74716fa.png)

and

![image](https://user-images.githubusercontent.com/1381702/30849221-ec7a9ddc-a2a1-11e7-88b8-370bea67f841.png)

A few questions for me to be able to handle this:

* What package version are you using? 
* TypeScript or JavaScript?

Regarding the difference between the spread import and namespace import - at the moment it won't make any difference when building your project. I agree that it is encouraged, but tree shaking won't work due to the way Babylon is currently built. When I get to the point that I have the time to fix the dependency tree, you will be able to benefit from it.

**Comment by zakhenry** [comment] 2017-09-26 09:05
@RaananW hmm, I just downloaded VS Code to check and the types are working ok, so this may be isolated to a Webstorm issue. I'll investigate further.

I'm using 
```
├── babylonjs@3.1.0-alpha3.5 
└── typescript@2.5.2 
```
with typescript (in an angular cli application)

Yea I understand tree shaking won't do much at the moment but if I use the right syntax it might just work some day for free ;)

**Comment by RaananW** [comment] 2017-09-26 09:09
@zakhenry , thanks for testing.

As I do want Webstorm users to benefit the new imports, it would be great if you can check what happened. Might be cached old declaration file? Or that Webstorm simply doesn't support export = BABYLON in a module declaration?

**Comment by zakhenry** [comment] 2017-09-26 09:18
@RaananW no problem, I've narrowed it down to the change that wrapped `export = BABYLON` with the declare module. This fixes the issue for me:

```ts
// declare module 'babylonjs' {
    export = BABYLON;
// }
```

**Comment by RaananW** [comment] 2017-09-26 09:24
That's interesting.

I will run a few tests on my side and see how we can make everything work correctly. We might get it to work with namespace exporting as well. 

I would expect all tools to work the same, but it seems like being naive is not a very smart thing to be :wink:

**Comment by zakhenry** [comment] 2017-09-26 09:25
Hah yea it is crazy considering Webstorm is using the TS language service, though perhaps not exclusively?

**Comment by RaananW** [comment] 2017-09-26 09:29
May I ask for the TS version as well? I was just thinking about this - I am actually using webpack to compile, so it has nothing to do with the IDE

**Comment by zakhenry** [comment] 2017-09-26 09:38
@RaananW yea I'm using `typescript@2.5.2 ` but I'm pretty sure that's not the reason as it compiles ok (angular cli also uses webpack under the hood). It must be related to how Webstorm links types. I might raise an issue on Webstorm if we can be sure it's the issue but in the meantime I think unwrapping the export results in correct behavior?

**Comment by RaananW** [comment] 2017-09-26 09:43
Nope, it doesn't. That's why I implemented this way. Removing the module declaration results in compilation errors due to the types not found in submodules. The submodules are using reference types (`/// <reference types="babylonjs"/>`) to assure they have the right references from babylon. It will work if you only use the core, but will break if you use any other module.

If it compiles, it is not a problem with typescript or the implementation. Seems like Webstorm doesn'T get along with export declaration in string-modules.

**Comment by zakhenry** [comment] 2017-09-26 09:46
@RaananW ah. yes you are right, I just tried manually editing the module declarations, and while Webstorm was happy, the compiler failed with post-process and loaders.

**Comment by RaananW** [comment] 2017-09-26 09:46
So it does seem to me like a webstorm issue. I wonder if other IDEs have the same problem

**Comment by zakhenry** [comment] 2017-09-26 10:52
@RaananW yep, definitely a Webstorm issue, interestingly I've discovered it partially works - I can click through to the definition of methods, but not classes, or properties of child members. 

If I uncheck use language service in Webstorm, it completely breaks, and errors are thrown throughout, so I suspect that Webstorm is running a hybrid of their own interpreter and the bundled language service.

I'll see if I can get a minimum reproduction without Babylon to show the Webstorm team

**Comment by zakhenry** [comment] 2017-09-26 11:51
@RaananW ok issue raised against Webstorm: https://youtrack.jetbrains.com/issue/WEB-28946

**Comment by zakhenry** [comment] 2017-09-28 11:49
@RaananW good news, turns out Webstorm has a fix in their latest EAP release

**Comment by RaananW** [comment] 2017-09-28 11:51
Awesome! So I can close this :smile:

**Comment by zakhenry** [comment] 2017-09-28 11:52
@RaananW uh yea, assuming this is why @deltakosh raised the issue in the first place? I kinda hijacked the issue sorry

**Closed by RaananW** 2017-09-28 11:51 UTC
Labels: enhancement
