### ISSUE TITLE
Add Rendering Mask Feature for GUI 

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#4924] opened 2018-08-12 13:27 UTC
Following http://www.html5gamedevs.com/topic/39384-gui-feature-request-mask/?tab=comments#comment-224840 it might be good to add a mask feature for Babylon GUI.

*We could integrate data structures for common shapes such as rectangle, circle and triangle, and use their data in the masking process. Maybe even just use the existing Rectangle and Ellipse containers for now if it'd make sense. Needless to say, nested scale, position and rotation will need to be taken into account - GUI already knows how to handle these, need to see how it can be integrated into the masking process.*

**Comment by sebavan** [comment] 2018-08-12 14:46
https://github.com/BabylonJS/Babylon.js/issues/3897

**Comment by deltakosh** [comment] 2018-12-10 22:53
Closing as duplicate of #3897

**Closed by deltakosh** 2018-12-10 22:53 UTC
Labels: enhancement, gui, help wanted
