### ISSUE TITLE
[v3.1-alpha] Inspector fails to load after physics impostor is added to externally-loaded mesh

### ISSUE THREAD

**Issue by treefort** [BabylonJS/Babylon.js#2839] opened 2017-09-21 04:07 UTC
I'm fetching a low-poly tree model from an external .obj file via the `AssetsManager` and adding a cylinder physics impostor after it has finished loading. All of this is working fine. Here's my tree:
![image](https://user-images.githubusercontent.com/1132492/30678302-3aa81490-9e5f-11e7-9f5c-dbc740d3ade1.png)
Next, I'm duplicating the tree and adding more because Bob Ross said they get lonely, but I digress.

Here's the code:
```
var loader = new BABYLON.AssetsManager(scene);
var tree = loader.addMeshTask("happyTree", "", "meshes/", "tree.obj");
loader.load();
tree.onSuccess = function (task) {
  var treeMesh = BABYLON.Mesh.MergeMeshes(task.loadedMeshes);
  treeMesh.material = treeMaterial;

  var tree1 = treeMesh.clone();
  treeMesh.dispose();

  tree1.position = new BABYLON.Vector3(-20, 17, 10);
  tree1.physicsImpostor = new BABYLON.PhysicsImpostor(tree1, BABYLON.PhysicsImpostor.CylinderImpostor, { mass: 0, restitution: 8 }, scene);
  ...
}
```

If I comment out the line where I assign `tree1.physicsImpostor`, the inspector loads fine. As it stands, this is what I'm seeing in the JS console:
![image](https://user-images.githubusercontent.com/1132492/30678433-3071847e-9e60-11e7-8dfb-1608b33d12ed.png)

I'm pulling down the relevant JS files from `preview.babylonjs.com` just to make sure I have the latest and greatest. Seen on Chrome v60.0.3112.101 on Windows 10.

This is the first issue I've filed in this repo, so please let me know if I've forgotten anything!

**Comment by RaananW** [comment] 2017-09-21 11:23
Hi @treefort ,

If Bob Ross said so, it must be done. Trees!!!

I can't seem to be able to reproduce this on the playground. Can you give it a try and see if you manage to share a public link where we can see it as well? Editable code (i.e. playground) would be wonderful.

Also - can you try not disposing the original object and see if it helps? No idea if that's the case here. And since localCompare is used during string-comparison, maybe try giving tree1 a name (the first variable in the clone function can be a string with an assigned name).

**Comment by Palmer-JC** [comment] 2017-09-21 15:05
Wow. People in Berlin know who Bob Ross is.

**Comment by treefort** [comment] 2017-09-25 03:37
>And since localCompare is used during string-comparison, maybe try giving tree1 a name

Nailed it! That fixed the issue.

Thanks! :D

**Comment by RaananW** [comment] 2017-09-25 13:39
@deltakosh , @Temechon ,

might be a good idea to fail silently if a mesh has no name.

**Comment by deltakosh** [comment] 2017-09-25 13:41
Agree. Let me reopen it for this fix

**Comment by QuentinRillet** [comment] 2017-10-12 14:15
Hi @treefort 

I'm checking this issue and I can't reproduce this bug.  Can you give me a playground with an example ?

**Comment by deltakosh** [comment] 2017-10-16 23:17
Up...

**Comment by treefort** [comment] 2017-10-17 03:12
@QuentinRillet here ya go: http://www.babylonjs-playground.com/#6C1FLA

1. Click "run"
2. Click "Debug layer"
3. Check JS console–
![image](https://user-images.githubusercontent.com/1132492/31645003-7d51703a-b2c7-11e7-8c0d-1d11da11bd31.png)

**Comment by deltakosh** [comment] 2017-10-30 23:18
Up @QuentinRillet  :)

**Comment by Temechon** [comment] 2017-10-31 08:39
Fixed in https://github.com/BabylonJS/Babylon.js/pull/3052

**Closed** 2017-10-31 13:50 UTC
Labels: bug, Inspector
