### ISSUE TITLE
Oimo.js Uncaught TypeError: Cannot read property 'pair' of undefined

### ISSUE THREAD

**Issue by alexcre8or** [BabylonJS/Babylon.js#5801] opened 2019-01-20 19:51 UTC
set variable cannon = false at line 80:
https://playground.babylonjs.com/#5W5B6W#1 

When trying to render step the engine is stoped and the following error occurred:

```
Oimo.js:1 Uncaught TypeError: Cannot read property 'pair' of undefined
    at nt.collectPairs (Oimo.js:1)
    at nt.detectPairs (Oimo.js:1)
    at Nt.step (Oimo.js:1)
    at e.executeStep (babylon.js:16)
    at e._step (babylon.js:16)
    at t.W.a._advancePhysicsEngineStep (babylon.js:16)
    at t.render (babylon.js:16)
    at index.js:601
    at e._renderLoop (babylon.js:16)
```

**Comment by BabylonJSGuide** [comment] 2019-01-21 15:42
have tried the above PG code locally using BJSv3.3, BJSv4.0.0-alpha21, with Oimo.js in dist folder Oimo33 and Oimo.js in dist/preview release folder (Oimo40)

results
BJSv3.3 and Oimo33 PG works
BJSv3.3 and Oimo40 PG not working
BJSv4.0.0-alpha21 and Oimo33 PG works
BJSv4.0.0-alpha21 and Oimo40 PG not working

So if these findings are confirmed it appears that the error appears in the newest version of Oimo.js in the dist/preview release folder

**Comment by BabylonJSGuide** [comment] 2019-01-21 16:50
Interestingly if I try the same with the files from https://github.com/lo-th/Oimo.js/tree/gh-pages/build 
with oimo.min.js same errors with BJSv3.3 and  BJSv4.0.0-alpha21

However with max version oimo.js with both BJSv3.3 and  BJSv4.0.0-alpha21 no console errors but the 'wheel' stops turning and all balls congregate beneath it unless you take the setMotor, second parameter up to at least 30 * forceFactor.

When you use the 2017 versions whether you use Oimo.js or Oimo.min.js they react in the same way with BJS3.3 and BJSv4.0.0-alpha21 as the current Oimo.js from the current Oimo.js github does with both BJS versions.

So it looks like a problem with the current minified version.

Pinging @sebavan who did the most recent commit for the Oimo.js github.

Hope this info might help.

**Comment by sebavan** [comment] 2019-01-21 17:03
I will take a look ASAP it is pretty strange min and max acts differently, I simply build with the embedded built process :-( I ll investigate and let you know.

**Comment by BabylonJSGuide** [comment] 2019-01-21 17:07
👍

**Comment by sebavan** [comment] 2019-01-21 17:32
Looks like the uglify compress option does break the lib for some reason, I ll try to rely on the default rollup minification plugin instead and see what it gives

**Comment by sebavan** [comment] 2019-01-21 19:59
Addressed in oimo by lo-th/Oimo.js#85 and fixed by the previous PR

**Closed by sebavan** 2019-01-21 19:59 UTC
Labels: bug
