### ISSUE TITLE
Audio does not unlock on iOS.

### ISSUE THREAD

**Issue by svanderbeck11** [BabylonJS/Babylon.js#8115] opened 2020-05-06 16:59 UTC
- Bug repro on:  https://www.babylonjs-playground.com/#PCY1J#90
- Expected result: Audio should play on iOS after being unlocked.
- Current result: Audio does not play on iOS after unlock

Bug happens on iPhone 11, iOS 13.3.1. 
Everything works fine on iPad 5th Gen, iOS 12.4.1

**Comment by svanderbeck11** [comment] 2020-05-06 17:02
Also works fine on iPad 6th gen. iOS 13.3.1

**Comment by sebavan** [comment] 2020-05-06 19:33
@svanderbeck11 I am unfortunately not able to repro on ios 13.3.1 and do not have any other devices to try it on at the moment. Is is only on Iphone 11 ??? cause it looks like the audio stack for ios might have an issue.

I ll see on my side if i can find a 11 to try it on.

**Comment by sebavan** [comment] 2020-05-06 19:34
ohhh and also double check you are not on silent mode, I looked 2 hours last time due to that... it can happen :-)

**Comment by sebavan** [comment] 2020-05-06 19:49
ok and another one can not repro either. I am closing the issue for now and let s discuss on the forum to find the root cause  ?

**Closed by sebavan** 2020-05-06 19:49 UTC
Labels: audio, bug, in progress, unable to reproduce
