### ISSUE TITLE
Add Parallax occlusion to the PerturbNormal node

### ISSUE THREAD

**Issue by unicomp21** [BabylonJS/Babylon.js#10258] opened 2021-04-26 10:41 UTC
https://forum.babylonjs.com/t/nodematerialeditor-and-parallax-occlusion/19962/2

**Comment by deltakosh** [comment] 2021-04-26 14:47
Closed with #10257

**Comment by deltakosh** [comment] 2021-05-13 18:32
Ok I've checked feasibility and it is far more complicated that I initially thought.
The problem is that parallax need to read from the normal maps multiple times (it is sampling the pixel environment to compute the parallax effect) and this is not how NME works unfortunately so the only possible way would be to duplicate the texture node to create the PerturbNormalWithParallax node but this seems overkill.

So I'm closing this issue as it will not be supported any time soon :(

**Closed by deltakosh** 2021-05-13 18:32 UTC
Labels: help wanted, nme
