### ISSUE TITLE
Add full support for ES6 modules (for Gui and Inspector)

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#3314] opened 2017-12-06 00:44 UTC
Let's open the door to tree Shacking ;)

**Comment by RaananW** [comment] 2018-01-10 20:20
Starting 3.2.0-alpha2 on NPM we have es6 modules available in beta. I am keeping this open until I am satisfied there are no bugs.

**Comment by edzis** [comment] 2018-01-10 21:56
@RaananW I get `TypeError: Cannot set property 'FreeCameraGamepadInput' of undefined`.

I think this is because `CameraInputTypes` is not defined.
When [searching in the resulting JS code](https://github.com/BabylonJS/Babylon.js/search?l=JavaScript&q=CameraInputTypes&type=&utf8=%E2%9C%93) I can not find where it is created.

**Comment by RaananW** [comment] 2018-01-10 22:00
Thanks!
CameraInputTypes is a part of the targetCamera module, which the FreeCamera depends on. let me check why it is not automatically included.
Could you try importing CameraInputTypes from "targetCamera" and see if it exists?

**Comment by RaananW** [comment] 2018-01-10 22:03
I assume you are using es6, and I believe I know what the problem is. Fix is coming soon, thanks for reporting!

**Comment by edzis** [comment] 2018-01-10 22:04
That is what I just tried and got by bay adding 

    import { CameraInputTypes } from 'babylonjs/targetCamera'
    console.log('CameraInputTypes', CameraInputTypes)

in front of my import of `Gamepad`

But now getting other errors which I will look into working around and report back here.

**Comment by edzis** [comment] 2018-01-10 22:07
Next one I get is 

    Uncaught TypeError: BABYLON.VRExperienceHelper is not a constructor
    at Scene../node_modules/babylonjs/core/index.js.Scene.createDefaultVRExperience

`VRExperienceHelper` is not imported in `core`.

**Comment by RaananW** [comment] 2018-01-10 22:13
Core will have a few classes missing, that will need to be imported and added. This will be a part of the documentation when I write it.
We do try to prevent importing everything to core while still keeping backwards compatibility. The Scene will slowly be cleaned from unneeded dependencies, but for now we will need to import those missing classes.

And I just noticed I have a small bug with es6 libs that depend on modules that are not core. Which will probably be the main source of errors in es6.

**Comment by edzis** [comment] 2018-01-10 22:20
I will look out for any es6 updates and test again.

Not sure if this is helpful now, but I just noticed that after switching to es6 babylon on my 10 files the production bundle grew quite a bit - `850.62 KB (+283.2 KB)  build/static/js/main.c19e52b2.js`

**Comment by RaananW** [comment] 2018-01-10 22:44
Thanks for the info, I will keep you updated here.
Quick question - what lib are you using to bundle your package?

**Comment by edzis** [comment] 2018-01-11 10:13
I am using webpack as configured by Create React App with TypeScript support

`create-react-app my-app  --scripts-version=react-scripts-ts`

**Comment by Kaffesumpen** [comment] 2018-01-14 21:55
`import { ArcRotateCamera } from '../node_modules/babylonjs/arcRotateCamera/es6.js'`
gives error
`Uncaught TypeError: Failed to resolve module specifier 'babylonjs/targetCamera/es6'`
as on line 19, there is:
`import * as targetCamera from 'babylonjs/targetCamera/es6';`
I'm not using any bundler, so I am curios is this a oversight or will I not be able to use native js?

**Comment by RaananW** [comment] 2018-01-15 11:01
Wow, super question!!

I believe that eventually we will support native javascript with es6 and leave commonjs to the bundlers. That's the entire point of supporting es6 :smile:
The problem is the lack of standard (at least one that I know of) in terms of location of the js files. Should I add "./node_modules/", should I create a form of a packer? All interesting questions that will be slowly answered! 

We have internally decided to first support es6 with a single large file (the entire framework with es6 exports), so people will be able to start working with native es6. 

Most bugs were already eliminated (but not yet merged), and I am working on a solution for circular dependencies. It will sadly take longer than I expected...

**Comment by edzis** [comment] 2018-01-17 11:26
@RaananW I just upgraded to alpha4 and it fails to locate modules:

    import { Engine, Scene, Texture, Tools } from 'babylonjs/core'
results into

    [ts] Cannot find module 'babylonjs/core'

**Comment by RaananW** [comment] 2018-01-17 14:19
Until I fix the entire build process, I have decided to remove the modules. Instead of using `babylonjs/core` , please use `babylonjs` . It will load the entire framework. It is not optimal, but it works and tested. Native es6 can be loading using:
`import { Whatever } from 'babylonjs/es6'`

I will keep this thread updated when the modules are back and working. Sorry about the hassle!

**Comment by cruzdanilo** [comment] 2018-03-05 22:57
using webpack:
```javascript
import { Space } from 'babylonjs/es6';
console.log(Space); // undefined
```
gives:
```
WARNING in ./main.js
2:12-17 "export 'Space' was not found in 'babylonjs/es6'
 @ ./main.js
```

**Comment by deltakosh** [comment] 2018-03-06 01:10
Pinging @raananw

**Comment by RaananW** [comment] 2018-03-06 17:00
Problem found, I will take care of that until the next npm release.

**Comment by cruzdanilo** [comment] 2018-03-06 19:21
@RaananW, i also had to use this hack in my `webpack.config.js` for shaking off oimo and cannon:
```javascript
  plugins: [
    new DefinePlugin({ OIMO: JSON.stringify(true), CANNON: JSON.stringify(true) }),
  ],
```
webpack v4.1.0

**Comment by RaananW** [comment] 2018-03-06 19:37
I am planning on fixing the cannon and oimo dependencies in a different way. But a question - why are you using the es6 module if you use webpack? the UMD would fit much better. ES6 was mainly created for native es6 developers.

**Comment by cruzdanilo** [comment] 2018-03-06 19:49
i was just trying the new stuff :)
but the oimo/cannon hack is necessary using umd too.
also, it is less weird to write `import { Engine } from 'babylonjs/es6'` than `import { Engine } from 'babylonjs/babylon.max'`. the minified version gives less accurate build size stats.

**Comment by RaananW** [comment] 2018-03-06 19:53
(I am just asking, not criticizing at all :smile:).
What problem do you have with the minified version? not sure what you mean with the build size stats.

About Oimo and Cannon, I will soon add them as peer dependencies to the main engine so you can define them as externals in webpack.

**Comment by cruzdanilo** [comment] 2018-03-06 20:01
take a look at the demo here: https://chrisbateman.github.io/webpack-visualizer/
the 'actual vs raw' size is less accurate when using pre-minified code.

**Comment by cruzdanilo** [comment] 2018-03-06 20:11
nice source maps for debugging are also a huge plus.

**Comment by deltakosh** [comment] 2018-03-21 17:25
Moving to 3.3 as we need to refactor a lot of code

**Comment by robinfehr** [comment] 2018-03-25 20:52
@RaananW using a bundler e.g. webpack i guess is a good idea with the `es6` version here since not only can we do the tree-shaking that does include what we need but also eliminate the dead code and cut it from the files. therefore end up with a much smaller bundle. as of webpack4(i guess 4 :~)) there is also a option that can be added to the package.json to tell the bundler about sideEffects and make the dead code deleteable by default if not imported.  therefore specifying the files as sideEffectFree if thats the case could drastically reduce the bundle size.

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by kutomer** [comment] 2018-04-02 10:49
@RaananW That's awesome, the way I see it this is the most important feature you guys can add to babylonjs.
currently `babylonjs` source code is 64.4% (3.2.0-beta.4 without physics engine - 1.86mb) of my bundle.
Can't wait for this feature to be released officially, so keep up the good work :)
 
When I try to import modules from `babylonjs/es6` I get an error message - 
```
error TS7016: Could not find a declaration file for module 'babylonjs/es6'. '/.../node_modules/babylonjs/es6.js' implicitly has an 'any' type.
  Try `npm install @types/babylonjs/es6` if it exists or add a new declaration (.d.ts) file containing `declare module 'babylonjs/es6';`
```

Any thoughts?
Tomer

**Comment by brian-hay** [comment] 2018-04-09 22:39
I assume this error is related to the discussion here and I don't need to create a new issue?

```
./node_modules/babylonjs/babylon.js
Module not found: Error: Can't resolve 'oimo' in '/path/to/myproject/node_modules/babylonjs'
```

**Comment by deltakosh** [comment] 2018-04-10 00:01
Pinging @raananw

**Comment by pascalbayer** [comment] 2018-05-01 16:47
Just gave a try to the new `babylonjs/es6` exports in my current @angular/cli project.

Interestingly I get following results:

- By using `import { ... } from babylonjs`:
  chunk {0} main.61b98ec05caa35572b25.bundle.js (main) 2.96 MB [initial] [rendered]
  Build time: 72122ms
- By using `import { ... } from babylonjs/es6`:
  chunk {0} main.2245515331547351e3e7.bundle.js (main) 4.81 MB [initial] [rendered]
  Build time: 166363ms

**Comment by RaananW** [comment] 2018-05-01 17:35
Hi @pascalbayer, are you using any other package (loaders, gui, etc) ? since they are not yet es6-enabled, they will load the UMD dependency, so Babylon will technically be included twice. Could that be the case here?

To everyone following this open issue - First, sorry for answering so late. I wish I had better news regarding full framework support of es6. Since out typescript codebase is not es6-compatible we need to refactor a lot of the code to get full support (including typescript declaration, for example). This will take some times, but we are all very much eager to get this feature to you as soon as possible.

My recommendation to everyone would be to use typescript with commonjs using our fully-supported AMD module. you will still be able to import from "babylonjs" and all of its modules, so you can still write es6 code. Using the es6 module is actually only needed if you write es6-code only and are planning on serving es6 to your users. The rest can be done the same using UMD.

@brian-hay - this is actually not related to this issue - you are using babylon.js which is our UMD file. To solve this see here - http://doc.babylonjs.com/features/npm_support#using-webpack

**Comment by pascalbayer** [comment] 2018-05-01 17:59
@RaananW Yes, that is actually the case, I 'm including loaders and materials, did a quick check and disabled the two and it worked.

Thanks for the update and the good work. Let me know if there is anything I can do to contribute to a faster es6 feature completion.

**Comment by kutomer** [comment] 2018-05-30 18:45
@RaananW Hey, any updates on this one? Need any help?

**Comment by RaananW** [comment] 2018-05-30 19:04
not yet done. as this requires a major change in our codebase. When we'll start working on it I will make sure to reference this issue

**Comment by BrainBacon** [comment] 2018-06-29 20:14
Hey guys, I'm looking to get the `babylonjs-loaders` extension integrated into the es6 build for the `Vue-BabylonJS` plugin. Right now without it I am unable to proceed with [creating an asset component](https://github.com/Beg-in/vue-babylonjs/issues/2).

From what I understand about the goals with the es6 build, shouldn't all of the first-party extensions just be included in the build? Couldn't one use tree-shaking to just omit that functionality when consuming the library as an ES Module?

Specifically with `babylonjs-loaders` is something blocking including that particular extension? Can I tackle some refactoring tasks to speed up that piece?

**Comment by deltakosh** [comment] 2018-06-29 20:20
Just to make sure: why not referencing both?

**Comment by BrainBacon** [comment] 2018-06-29 20:40
From my experiments with including the `babylonjs-loaders` dependency with the es6 build it seems like an incredible amount of code is being loaded and ended up crashing my Rollup build. Even when I increased the memory limit for Rollup, the resulting bundle size was so great as to crash Webpack in my tests. I assumed this was because Babylon.js is being included twice; by the es6 build and the standard build imported by `babylonjs-loaders`.

**Comment by deltakosh** [comment] 2018-06-29 20:41
Pinging the master of modules @RaananW

**Comment by BrainBacon** [comment] 2018-06-29 20:49
Actually, a quick thought; I know this wouldn't solve every use-case, but would it be useful to produce a Webpack Loader in addition to the standard client-side loaders? I'm thinking it would be really efficient to convert `.obj`, `.stl`, and `.gltf` assets to modules or `.babylon` at build time. Obviously this wouldn't help with assets hosted by third-parties, but would save compute cycles on clients that host their own assets.

**Comment by FlynnTheInfinite** [comment] 2018-07-15 11:51
not sure if it's really related, but when I imported babylonjs from yarn, I got these errors :

./node_modules/babylonjs/babylon.js
Module not found: Can't resolve 'cannon' in 'C:\Users\Fabien\Documents\Sensuba\V3\Project\webapp\node_modules\babylonjs'

./node_modules/babylonjs/babylon.js
Module not found: Can't resolve 'earcut' in 'C:\Users\Fabien\Documents\Sensuba\V3\Project\webapp\node_modules\babylonjs'

./node_modules/babylonjs/babylon.js
Module not found: Can't resolve 'oimo' in 'C:\Users\Fabien\Documents\Sensuba\V3\Project\webapp\node_modules\babylonjs'

**Comment by BrainBacon** [comment] 2018-07-15 19:57
@FlynnTheInfinite It's because cannon, earcut, and oimo are now optional peer dependencies. You can add them to your project dependencies and the UMD module definition should pick them up. There's more details [in the documentation](https://doc.babylonjs.com/features/npm_support).

**Comment by RaananW** [comment] 2018-07-16 09:49
We are slowly moving the modules to es6-style code. GUI and Inspector will soon be integrated, next are the materials and loaders - https://github.com/BabylonJS/Babylon.js/pull/4738

**Comment by kutomer** [comment] 2018-08-05 09:31
@RaananW Hey, Thanks a lot for that!
But not sure how to use it, I'm using version `3.3.0-alpha.15`
When I try to import the module: `import { AdvancedDynamicTexture } from 'babylonjs-gui/2D/advancedDynamicTexture';` I get no definition errors.
But when I try to compile I get the following error:
```
Failed to compile.

Module not found: Error: Can't resolve 'babylonjs-gui/2D/advancedDynamicTexture' in ...
```

Not sure how it suppose to work, but I expected the node_module dir to look something like lodash.

**Comment by RaananW** [comment] 2018-08-05 10:12
Hi,

The GUI's package is still a umd package. The next step, until 3.3.0 official release, is to also include an es6 compatible bundle which will allow you to do what you are trying to do. ATM you still need to import everything from "babylonjs-gui". 

NPM will include both umd and es6, so you will be able to choose what you are using. It's use the "esnext" and "module" tag to separate the two.

**Comment by kutomer** [comment] 2018-08-05 12:16
@RaananW Thanks for your quick reply, but not sure I fully understood what you meant :)
How do I select the es6 bundle?
I don't see any "es6" bundle in babylonjs-gui folder in node_modules (version alpha.15)
![screen shot 2018-08-05 at 15 15 18](https://user-images.githubusercontent.com/3729904/43685799-7a137d00-98c2-11e8-9eba-b31a7396c653.png)

**Comment by RaananW** [comment] 2018-08-05 18:08
There isn't any es6 package yet. This is the next step, after converting the code to es6 compatible. I'll update better when we deliver the es6 bundle. At the moment it's umd only

**Comment by kutomer** [comment] 2018-08-06 15:42
So now `import { AdvancedDynamicTexture } from 'babylonjs-gui';` should trigger tree shaking?

**Comment by deltakosh** [comment] 2018-08-06 15:46
It will as soon as we will finish this task

**Comment by deltakosh** [comment] 2018-08-22 15:52
Hey @RaananW, do you think this could be done for 3.3 time frame?

**Comment by kutomer** [comment] 2018-11-14 11:02
Hey guys, sorry for being such a nag, but do you think it will be ready for 4.0?

**Comment by deltakosh** [comment] 2018-11-14 15:10
Oh yeah :)
Check this branch: https://github.com/BabylonJS/Babylon.js/tree/libToModules

**Comment by kutomer** [comment] 2018-11-15 08:12
Thanks, I will :)

**Closed** 2019-01-09 18:19 UTC
Labels: build, enhancement

**Comment by RaananW** [comment] 2019-01-10 13:08
What a journey 😄

**Comment by Seanmclem** [comment] 2019-08-25 21:00
Still doesn't seem to work with StencilJs

**Comment by VaidasDatenis** [comment] 2020-03-13 18:39
Hey guys. What to do with this? I'm using Angular9, NativeScript 3.7 and BabylonJS-GUI npm package.
```
ERROR in node_modules/babylonjs-gui/babylon.gui.module.d.ts:127:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

127     import { Vector2 } from "babylonjs/Maths/math.vector";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:311:46 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

311     import { Vector2, Vector3, Matrix } from "babylonjs/Maths/math.vector";
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:320:30 - error TS2307: Cannot find module 'babylonjs/Maths/math.viewport'.

320     import { Viewport } from 'babylonjs/Maths/math.viewport';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:651:38 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

651     import { Vector2, Vector3 } from "babylonjs/Maths/math.vector";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:1749:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

1749     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:1882:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

1882     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:2032:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

2032     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:2326:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

2326     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:2330:28 - error TS2307: Cannot find module 'babylonjs/Maths/math.color'.

2330     import { Color3 } from 'babylonjs/Maths/math.color';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:2444:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

2444     import { Vector3 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:2512:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

2512     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:2639:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

2639     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:2688:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

2688     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:3053:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

3053     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:3087:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

3087     import { Vector2 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:3454:33 - error TS2307: Cannot find module 'babylonjs/Misc/perfCounter'.

3454     import { PerfCounter } from "babylonjs/Misc/perfCounter";
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:3643:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

3643     import { Vector3 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:3718:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

3718     import { Vector3 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:3738:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

3738     import { Vector3 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:3972:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

3972     import { Vector3 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:4026:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

4026     import { Vector3 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:4060:37 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

4060     import { Vector3, Matrix } from "babylonjs/Maths/math.vector";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:4068:36 - error TS2307: Cannot find module 'babylonjs/Maths/math.color'.

4068     import { Color3, Color4 } from 'babylonjs/Maths/math.color';
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:4263:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

4263     import { Vector3 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:4274:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

4274     import { Vector3 } from "babylonjs/Maths/math.vector";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/babylonjs-gui/babylon.gui.module.d.ts:4294:29 - error TS2307: Cannot find module 'babylonjs/Maths/math.vector'.

4294     import { Vector3 } from "babylonjs/Maths/math.vector";
```

**Comment by sebavan** [comment] 2020-03-13 19:31
Why not relying on the es6 packages ???

**Comment by sebavan** [comment] 2020-03-13 21:14
And I guess your issue comes from 
```import 'babylonjs-materials';```

Which creates conflicts on the namespace you should try 
```import * as MAT from 'babylonjs-materials';```

**Comment by VaidasDatenis** [comment] 2020-03-14 06:32
i'm trying to use package 
```https://www.npmjs.com/package/babylonjs-gui```
and use this template:
```https://doc.babylonjs.com/how_to/gui3d```.
My tsconfig.json:
```
"types": [
      "babylonjs",
      "babylonjs-gui",
      "babylonjs-material"
  ],
  "target": "es6
```

**Comment by sebavan** [comment] 2020-03-14 11:14
Could you use the forum https://forum.babylonjs.com/ ? To share a repro and we ll continue the discussion there. We only use Github for bugs or validated feature requests. Thanks a lot :-)
