### ISSUE TITLE
Allow storing sounds offline

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Babylon.js#3230] opened 2017-11-24 09:23 UTC
Sounds are not cached in the indexeddb. A new flag can be added to the manifest to allow storing sounds offline for future use.

**Comment by davrous** [comment] 2017-11-29 15:21
Well, sounds are stored in IDB if you're using a .manifest file such as in the Mansion demo: http://www.babylonjs.com/demos/mansion/

It's currently stored in the "versions" table as I never updated the schema to create a new table (had too many bugs in iOS/Chrome in the schema updating process when I tried it a couple of months ago)

I would then suggest to:

- create a new property for sound in the manifest
- create a new table in the DB for sounds
- create a new table in the DB for misc files

**Comment by deltakosh** [comment] 2017-12-07 22:42
Closing this one as duplicate of #3340

**Closed by deltakosh** 2017-12-07 22:42 UTC
Labels: audio, enhancement
