### ISSUE TITLE
GLTF Exporter incorrect rendering

### ISSUE THREAD

**Issue by luruke** [BabylonJS/Babylon.js#8514] opened 2020-07-09 10:39 UTC
Hello,
I'm experiencing issues with the glTF Exporter (https://doc.babylonjs.com/extensions/gltfexporter).

My current project is running 3.3.0,
here's how the scene looks like vs the .glb file exported (viewed via babylon sandbox)

![Screenshot 2020-07-09 at 12 27 35](https://user-images.githubusercontent.com/61326/87028947-aa76c680-c1df-11ea-8138-e2ce9253261c.png)

The surrounding box that is `isVisible = false` in the code doesn't seems to match the gltf
![Screenshot 2020-07-09 at 12 29 06](https://user-images.githubusercontent.com/61326/87029037-d5f9b100-c1df-11ea-90b8-1e16cc9063f2.png)

Even after i hide the box the model doesn't looks correct. I assume UV/Texture match are wrong?
![Screenshot 2020-07-09 at 12 29 15](https://user-images.githubusercontent.com/61326/87029140-ffb2d800-c1df-11ea-895e-48863b0ef103.png)

To run a test I upgraded my whole project to 4.1.0. The glb file exported is smaller compared to 3.3.0 (21mb vs 36mb) and apparently it's missing a texture, 
![Screenshot 2020-07-09 at 12 31 38](https://user-images.githubusercontent.com/61326/87029255-2b35c280-c1e0-11ea-8e76-3f2cebb2d751.png)

If I ignore this and open on blender, i can still see that uv/textures are wrong:
![Screenshot 2020-07-09 at 12 35 55](https://user-images.githubusercontent.com/61326/87029695-c75fc980-c1e0-11ea-8fdf-e524da4f3b4d.png)

Unfortunately the project is a bit complex to provide a small contained jsfiddle to replicate this, but you can see the project live at https://www.mobitec.be/fr/configurateur/chaise/pure-c08?department=&upholstery=simili&data=%7B%221%22%3A694,%222%22%3A48%7D

Is this is a known bug, any advice/pitfall or something to avoid when using glTF exporter?

**Comment by Drigax** [comment] 2020-07-09 21:43
Thanks for the report,

Currently visibility is not supported in glTF, we currently export all nodes in scene regardless of whether they are enabled/disabled. Adding @bghgary, do you think this is correct behavior, or should we rather omit exporting disabled nodes?

regarding the improper UV mapping, and texture issues, we've definitely made a number of changes to the glTF exporter since 3.3.0, and since 4.1.0, can you reproduce any of this behavior in a playground? Its a bit hard to reproduce this only from description without any sample asset or process to round-trip through Babylon.js

**Comment by bghgary** [comment] 2020-07-09 22:02
> do you think this is correct behavior, or should we rather omit exporting disabled nodes?

We have a [callback function](https://doc.babylonjs.com/api/interfaces/babylon.iexportoptions#shouldexportnode) that allows people to add code to determine what is exported. This callback can be used to filter out the invisible or disabled nodes. It might be okay to do this by default, but there should be a way to opt-out. It is a bit difficult to determine what should be exported or not since every scenario is different.

**Comment by luruke** [comment] 2020-07-10 07:03
Thanks @Drigax , I will try to provide a small playground to replicate this.

**Comment by luruke** [comment] 2020-07-15 09:31
Hello @Drigax.
I just created a small playground around this: https://github.com/luruke/test-babylon-export-gltf

Basically at export, a texture is missing. Depending on the n.of meshes , the missing texture may vary (maybe something due texture uniform index?).

![Screenshot 2020-07-15 at 11 16 52](https://user-images.githubusercontent.com/61326/87528878-73e0f600-c68e-11ea-88f7-6ed40bda672e.png)

![Screenshot 2020-07-15 at 10 52 44](https://user-images.githubusercontent.com/61326/87528839-61ff5300-c68e-11ea-96ba-75f6cfc4e5c1.png)

**Comment by luruke** [comment] 2020-07-28 07:25
Hello @Drigax , wondering if you were able to replicate this, and if I can help you somehow.

**Comment by Drigax** [comment] 2020-08-12 02:47
Hi @luruke, can you make your loading logic work via: playround.babylonjs.com?

**Comment by Drigax** [comment] 2020-08-12 17:23
@deltakosh, can you take a look at this instead? this environment is a bit unusual, I'm strugging to actually debug it.

**Comment by deltakosh** [comment] 2020-08-12 17:29
@luruke can you share the PG code even if it is not working?

**Comment by luruke** [comment] 2020-08-12 17:41
@deltakosh  / @Drigax the repo contains exactly that:
https://github.com/luruke/test-babylon-export-gltf/blob/master/index.html#L66
It's a local copy of the playground

You can just download the index.html and run it on a web server

**Comment by deltakosh** [comment] 2020-08-12 18:10
yes but we need it inside the PG to remove all other error inducing sources

**Comment by luruke** [comment] 2020-08-12 21:14
@deltakosh , https://playground.babylonjs.com/#7T1HBH

**Comment by Popov72** [comment] 2020-08-12 21:45
Here's what I get when running the PG in my local repo (I have just synced my repo with the master, so it is up to date):
![image](https://user-images.githubusercontent.com/4152247/90071061-360ad800-dcf5-11ea-868d-a2e6726f5e19.png)

However, I do also have this error with the PG online:
![image](https://user-images.githubusercontent.com/4152247/90071115-48851180-dcf5-11ea-9083-919e837d335d.png)

**Comment by deltakosh** [comment] 2020-08-13 17:06
Here is the fix of the PG:
https://playground.babylonjs.com/#7T1HBH#1

See line #214 where I set up the gltf extension

**Comment by luruke** [comment] 2020-08-13 19:07
Ah great, thank you @deltakosh.

I have added the generation of the glb on the PG:
[https://playground.babylonjs.com/#7T1HBH#2](https://playground.babylonjs.com/#7T1HBH#2)


```

                document.addEventListener('click', () => {
                    BABYLON.GLTF2Export.GLBAsync(scene, "file").then((glb) => {
                        glb.downloadFiles();
                    });
                })

```

1. Once the scene is loaded, click anywhere to download the glb file
2. Verify that the glb has incorrect texture

**Comment by deltakosh** [comment] 2020-08-13 19:09
@Drigax interested in taking from here?

**Comment by luruke** [comment] 2020-08-24 07:03
Hello @deltakosh / @Drigax , any info on this?
happy to help if you need more information

**Comment by deltakosh** [comment] 2020-08-24 16:31
Pinging @Popov72 to see if he can quickly check

**Comment by Popov72** [comment] 2020-08-24 16:43
I will have a look asap.

**Comment by Popov72** [comment] 2020-08-25 15:47
For some reason, disabling the occlusion texture for the two materials that you recreate from an external json file make it work (line 243 and 258):

https://playground.babylonjs.com/#7T1HBH#19

Those materials are created as PBRMetallicRoughnessMaterial, contrary to the other materials that are PBRMaterial.

Still investigating...

Note: that even when it works, the texture is not tiled as it is in the PG, but I think it's another issue.

**Comment by Popov72** [comment] 2020-08-25 17:26
So, your occlusion texture is not right:

https://playground.babylonjs.com/#7T1HBH#21

By default, the occlusion map is not applied for direct lighting (intensity=0). When using a PBRMetallicRoughnessMaterial, you can't change this property in a clean way because it is not exposed. However, you can directly change `_ambientTextureImpactOnAnalyticalLights` that exists on `PBRBaseMaterial`. That's what I did in the PG above.

As you can see, you get the same display than in the sandbox.

You will also get the same display in the PG by using an environment texture instead of a direct light:

https://playground.babylonjs.com/#7T1HBH#22

There's still a problem with some invalid textures being generated: it seems the bug does not show up when disposing of the previous material before replacing it for the feet / upholstery meshes:

https://playground.babylonjs.com/#7T1HBH#23

This PG does work and does not generate invalid picture files when creating the .glb

Still investigating this problem.

**Comment by Popov72** [comment] 2020-08-27 16:37
Fixed by #8824

**Comment by luruke** [comment] 2020-08-31 15:56
Thanks @Popov72 !
Will try to use latest nightly and let you know, but indeed seems fixed 👍

**Comment by thomlucc** [comment] 2020-09-08 18:07
Fixed!

**Closed by thomlucc** 2020-09-08 18:07 UTC
Labels: glTF
