### ISSUE TITLE
Babylon.js GLTF exporter

### ISSUE THREAD

**Issue by FreakTheMighty** [BabylonJS/Babylon.js#3247] opened 2017-11-29 18:13 UTC
It would be great if we could export GLTF from babylon.js. The particular use case this would enable is editing a 3D scene on multiple platforms. For example, I would like to allow a user to edit a scene in Unity, upload and edit it in on the web using babylon.js, then reload it in Unity.

Looks like three.js has done a fair amount of work on this issue, perhaps it is useful reference:
https://github.com/mrdoob/three.js/issues/11951

**Comment by innerground** [comment] 2017-11-29 18:40
A partial export is possible, but GLTF does not supports all the features of the Babylon format.

**Comment by ashutoshmaurya10** [comment] 2018-01-24 06:16
Hi
I am currently seeking help for : "issue with exporting indices in glTF Serializers #3598".
We are trying to export our .babylon file to .gltf and use it but we are getting GPU hang and invalidating resource issue.
Please advise on how to go about resolving/understanding the root cause for this issue.

Thanks & Regards
Ashutosh

**Comment by kcoley** [comment] 2018-01-24 06:29
Hi @ashutoshmaurya10 .  For your issue, the root cause seems to be because of MultiMaterials.  I am currently working on supporting that as well as StandardMaterials.  I currently have an issue tracking the progress on the glTF serializer #3601 .  I plan on getting a fix for MultiMaterials completed soon.  Feel free to raise any other issues you hit with this tool.  Thanks!

**Closed** 2018-01-26 20:52 UTC
Labels: enhancement, exporters

**Comment by FreakTheMighty** [comment] 2018-01-29 16:57
@deltakosh was this issue closed intentionally? It's still part of a milestone.

**Comment by FreakTheMighty** [comment] 2018-01-29 16:59
Ah, looks like this was closed in favor of #3601
