### ISSUE TITLE
DeviceSourceManager crashes if touch input was started before it

### ISSUE THREAD

**Issue by CoPrez** [BabylonJS/Babylon.js#9957] opened 2021-02-23 19:57 UTC
**Repro**
- [Bug repro on playground](https://www.babylonjs-playground.com/#6S4YDA#5)
- Expected result: The device input system should be able to be activated before, after, or during a touch event without concern for it causing an exception.
- Current result: If the touch event is in progress while you initialize the device input system it will throw an exception when the touch input ends. I originally found this issue on Babylon React Native and then found that it repro's in the Playground as well. It should however be noted that the exception occurs in a different location on Babylon React Native versus in the Playground.
  - Babylon React Native: [DeviceSourceManager::_removeDevice() line #174](https://github.com/BabylonJS/Babylon.js/blob/10cfc6880bd8c4637b7ae29331f48bd2d786af70/src/DeviceInput/InputDevices/deviceSourceManager.ts#L174)
  - Playground: [DeviceInputSystem::_pointerUpEvent() line #408](https://github.com/BabylonJS/Babylon.js/blob/10cfc6880bd8c4637b7ae29331f48bd2d786af70/src/DeviceInput/deviceInputSystem.ts#L408)

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.1
 - Browser Edge
 - Version 89.0.774.27

**Smartphone (please complete the following information):**
 - Device: Note 10+
 - OS: Android 10
 - Browser: Babylon React Native
 - 
**Additional context**
It isn't an issue with mouse pointer events as the pointer persists even after the pointer up event. It is only an issue with touch events. To simulate touch events on desktop you can open developer tools and click the "toggle device emulation" button ([more info](https://developers.google.com/web/tools/chrome-devtools/device-mode/)).

**Comment by PolygonalSun** [comment] 2021-02-24 17:32
So I was taking a look at the PG and I noticed that the EventListener in the code was set up to create a new DeviceSourceManager object each time the "touchstart" event was fired (when a touch event happens).  The DeviceSourceManager should only be created once and only if the given script/app needs to reference and handle inputs in a specific way.  Here's an example, using the DeviceSourceManager: https://www.babylonjs-playground.com/#6S4YDA#8

Given the repro, I've concluded that this is not a bug.

**Comment by CoPrez** [comment] 2021-02-24 17:45
@PolygonalSun, thanks for taking a look.

The playground scene is a simplification of the much more complex code in our app. The issue is specifically if DeviceSourceManager is initialized while a touch interaction is in progress (after the touch start and before the touch end event). In your edits to the playground scene you are initializing the DeviceSourceManager right at the beginning of the script before any touch interactions will have begun. In the playground that totally makes sense, but in the real world scenario where I found the issue we it's much more complex as the Babylon scene is a small part of the app and isn't always active and listening for input.

In the original PG scene it is indeed bad that the DeviceSourceManager is initialized multiple times, but you can see the exception thrown from the very first time you start a touch event. Which simulates the scenario in our real world app where the user may have already been in the middle of a touch interaction when the Babylon scene is initialized.

I re-wrote the PG scene a bit to address the DeviceSourceManager being initialized multiple times, but still have it only initialize after a touch has started and before it has ended: [https://www.babylonjs-playground.com/#6S4YDA#9](https://www.babylonjs-playground.com/#6S4YDA#9)

**Comment by ryantrem** [comment] 2021-02-24 17:58
As @CoPrez said, the underlying issue is that if you create a `DeviceSourceManager` while a finger is already down on the screen, then when you lift your finger an unhandled exception is thrown (from `DeviceInputSystem` in the browser, and from `DeviceSourceManager` in Babylon Native). We need to handle this scenario more gracefully (e.g. don't assume you have already observed a touchstart when observing a touchend).

**Comment by PolygonalSun** [comment] 2021-02-24 18:13
Okay, lemme take another look at things and see what's going on.

**Comment by PolygonalSun** [comment] 2021-02-24 22:25
The fix for this is currently in PR: https://github.com/BabylonJS/Babylon.js/pull/9964

**Comment by PolygonalSun** [comment] 2021-03-01 22:54
Closed as fixed

**Closed by PolygonalSun** 2021-03-01 22:54 UTC
Labels: bug, inputs
