### ISSUE TITLE
GIZMO removing depth buffer 

### ISSUE THREAD

**Issue by Roba1993** [BabylonJS/Babylon.js#6327] opened 2019-05-09 09:38 UTC
# Bug

- Bug repro on [playground](https://www.babylonjs-playground.com/#BF24BR#1):

- Expected result:
New/Additional Utility Layers with `autoClearDepthAndStencil` set to `false` should render objects with respecting the depth of the main scene. 

- Current result:
New/Additional Utility Layers are never respecting the depth of the main scene as soon as a `gizmoManager` is added to the scene.
To get the current result, just comment out the `gizmoManager` and it's working as expected.

**Comment by TrevorDev** [comment] 2019-05-09 18:10
@Roba1993 the cause of this seems to be that creating gizmoManager creates utilityLayers as well and one of the layers it creates does clear depth and this layer is currently being rendered before the layer you created. If you put your utility layer logic prior to creating the gizmoManager your layer will run first before the depth is cleared and hopefully work as expected.

See https://www.babylonjs-playground.com/#BF24BR#2

If you need further control I can expose the internal utility layers in the gizmo manager so you can reorder how the utility layers are rendered in so let me know.

**Comment by Roba1993** [comment] 2019-05-10 08:24
@TrevorDev  thank you for this really fast answer. For me personally, the solution should work. 

But still I think it's wrong, that one Layer can distrube the depth information from another layer. Maybe this should be changed/fixed in general. If you disagree, feel free to close this issue. If so, please add this information to the [documentation](https://doc.babylonjs.com/how_to/gizmo).

**Comment by TrevorDev** [comment] 2019-05-10 18:54
Glad that worked. Agreed its not ideal but since currently all layers share the same depth/color buffers order will matter and it is too big of a change right now to modify. I'll close this and update the docs for now and re evaluate once it becomes a blocker for someone.

**Closed by TrevorDev** 2019-05-10 18:54 UTC
Labels: bug
