### ISSUE TITLE
WebXRInput rapidly recreates Textures for hand tracking controllers whether or not hand tracking WebXR feature is enabled in BabylonReactNative

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/Babylon.js#10056] opened 2021-03-15 19:18 UTC
**Repro**
- Run BabylonReactNative Playground app on HoloLens 2 and enter immersive xr mode: https://github.com/BabylonJS/BabylonReactNative/tree/master/Apps/Playground 

**Additional context**
- Texture creation occurs for WebXRHandTracking sources whether or not WebXRHandTracking is enabled
- The texture creation is specifically kicked off by WebXRInput when observing that controllers have been added/removed. For whatever reason, a WebXR hand seems to register as a controller
- If I understand correctly, there may be 5+ textures created for the input source. None of these textures are currently used to display hand tracking meshes
- When hands are brought in and out of the scene (find and lose tracking) we get texture recreation. This causes rendering hiccups/poor performance. It seems like these textures should at least be cached so that we don't constantly recreate them. It is common for hands to lose tracking during normal application life cycles

**Comment by RaananW** [comment] 2021-03-16 16:10
I believe this should be divided to a few issues, but is not a bug.

1) The textures are coming from a motion controller that is created when the hands are detected. A motion controller is initialized to each input source in tracked-pointer mode that has the `.gamepad` object in it. A hand object doesn't have a `.gamepad` defined, but a `.hand` with different definitions (see the IDL here - https://www.w3.org/TR/webxr-hand-input-1/#idl-index). Could that be an issue in Native? 
2) We should make sure that hand meshes can be reused (the tracked meshes)  and are not disposed, especially since we expect to never hand more than 2 hands in the scene, and have one left and one right hand, which can be cached.

**Comment by chrisfromwork** [comment] 2021-03-16 16:34
We will use this issue to track material caching/avoiding creating textures/meshes for input sources that declare a hand property.

I've opened the following issue to track BabylonNative changes:
https://github.com/BabylonJS/BabylonNative/issues/635

**Comment by RaananW** [comment] 2021-04-08 10:45
Can this be closed?

**Comment by rickfromwork** [comment] 2021-04-09 23:32
Related, this issue tracks updating Babylon to not create controller models when a hand object exists, and anything else that needs to change with the knowledge that webXR now sends hand input with both a hand object and gamepad object.
#10144

**Comment by rickfromwork** [comment] 2021-12-03 00:48
@RaananW Is this now resolved with #10188, or should there be an additional change along the lines of enabling the caching by default for hands?

**Comment by RaananW** [comment] 2021-12-03 15:19
@rickfromwork - The hand meshes are not a part of the controller code and are therefore not cached in this issue that you mentioned.

The hand meshes (in the `WebXRHandTracking` feature) are not cached, but this would be a simple fix - cache them upon loading if not already cached. I can commit this change later today.

**Closed** 2021-12-06 09:04 UTC
Labels: VR/AR/XR, native
