### ISSUE TITLE
Some meshes to overlap glow

### ISSUE THREAD

**Issue by PixelsCommander** [BabylonJS/Babylon.js#4463] opened 2018-06-07 10:53 UTC
Imagine here the stroke behind chip stack is just absent as it would happen if stroke is overlapped by the stack. This is what I d like to achieve. Currently working on PR for this but would like to have some guidance/input.

My idea is to:
- API wise have additional flag ```shouldExcludedOverlap: boolean```
- Solution wise to render excluded meshes to one more stencil buffer and substract it from blurred glow texture.

Any better ideas on this? @deltakosh @sebavan

**Comment by deltakosh** [comment] 2018-06-07 17:08
Hey and thank you for your interest :)
How can you have more than one stencil buffer?

**Comment by PixelsCommander** [comment] 2018-06-07 17:50
Oh. I am still bad in buffers. Lets name it a texture which we substract from blurred one.

**Comment by deltakosh** [comment] 2018-06-07 17:53
ok so we are on the same page :D
let's do a PR please

**Comment by PixelsCommander** [comment] 2018-06-11 12:33
@deltakosh @sebavan  any ideas on how EffectLayer can render into two textures during single pass depending on some mesh property?

**Comment by deltakosh** [comment] 2018-06-15 03:57
Up? I guess rewrite the mesh you want in the rendertarget before applying the glow should do the trick

**Comment by PixelsCommander** [comment] 2018-06-15 10:13
TBH I tried to play around but so far cant make it work with both innerglow / outerglow. 

Rewrite? Could you elaborate here please?

**Comment by deltakosh** [comment] 2018-06-15 12:50
Just a thought but you should be able to render the object you want to overlap directly (as black objects) into the rendertarget texture just before applying the glow in the main scene (in order the remove the glow where they are)

**Comment by PixelsCommander** [comment] 2018-06-18 16:29
@deltakosh this works for outer glow but not for inner glow. These are shots from Spector:

Outline layer drawn correctly:
<img width="151" alt="screen shot 2018-06-18 at 5 36 34 pm" src="https://user-images.githubusercontent.com/810671/41548936-9b49a6de-7324-11e8-8b3c-62489ba4ad4f.png">

Outer glow drawn correctly then inner glow which spoils the picture:
<img width="151" alt="screen shot 2018-06-18 at 5 36 45 pm" src="https://user-images.githubusercontent.com/810671/41548946-a05bd1ba-7324-11e8-9a1e-ca6742d39cc7.png">

Also I observe some problems with depth buffer. So if I move camera a bit then it looks like:
<img width="271" alt="screen shot 2018-06-18 at 6 25 31 pm" src="https://user-images.githubusercontent.com/810671/41549109-129d6e14-7325-11e8-97d3-a5b08bccf796.png">

The code added is:

```Object.keys(this._excludedMeshes).forEach(id => {
                    this._renderPhase = RenderPhase.CleaningExcluded;

      var mesh = this._excludedMeshes[id].mesh;
      var subMeshes = mesh.subMeshes;
      var engine = this._engine;
      var previousStencilFunction = engine.getStencilFunction();
      var previousStencilOperationPass = engine.getStencilOperationPass();
      var previousStencilOperationFail = engine.getStencilOperationFail();
      var previousStencilOperationDepthFail = engine.getStencilOperationDepthFail();
      engine.setStencilFunction(Engine.ALWAYS);
      engine.setStencilOperationPass(Engine.ZERO);
      engine.setStencilOperationFail(Engine.ZERO);
      engine.setStencilOperationDepthFail(Engine.ZERO);
      subMeshes.forEach(this._renderSubMesh.bind(this));
      engine.setStencilFunction(previousStencilFunction);
      engine.setStencilOperationPass(previousStencilOperationPass);
      engine.setStencilOperationFail(previousStencilOperationFail);
      engine.setStencilOperationDepthFail(previousStencilOperationDepthFail);
      this._renderPhase = RenderPhase.InnerGlow;
   });```

Any suggestions?

**Comment by sebavan** [comment] 2018-06-18 19:55
Another idea would be to render the chip after the first renderLayer to hide to border.

You could rely on a second renderGroup without cleaning the depth info ?

Let me try to do a quick PG

**Comment by sebavan** [comment] 2018-06-18 23:30
@PixelsCommander looking more in detail in the issue, the best way to fix it would be to allow effect layer to work per rendering group.

Thinking even deeper there are a couple of other nice changes we could do in this space.

If you are not in a rush I am planing to deploy a new version by end of week. Would that fit to you ?

**Comment by sebavan** [comment] 2018-06-18 23:31
Closed and reopen due to finger management issue ;-)

**Comment by PixelsCommander** [comment] 2018-06-19 08:15
Yeah, sure.

**Comment by sebavan** [comment] 2018-06-22 22:35
It happens than the changes I am doing to componentize the effectlayers are getting a bit bigger but will help componentizing other modules.

I am expecting to have this for end of next week. Basically, you would be able to associate the effect layers with a rendering group ensuring that from one group to the other you could render on top of the effect.

**Comment by PixelsCommander** [comment] 2018-06-22 23:31
Sounds great. Looking forward for it!

2018-06-23 0:35 GMT+02:00 sebavan <notifications@github.com>:

**Comment by sebavan** [comment] 2018-06-29 02:21
Following the PR above, you ll be able to achieve this through the use of rendering groups:
https://playground.babylonjs.com/#KTR4V2

Basically you can attach an effect layer to a chosen rendering group and push the meshes that needs to overlap in a subsequent group.

Also, please turn off the auto clear for the second group or those meshes will draw on anything present in the first one as the depth buffer would be clear.

I close the issue for now and we can open it back if needed.

**Closed by sebavan** 2018-06-29 02:21 UTC
Labels: enhancement, in progress, rendering engine

**Comment by PixelsCommander** [comment] 2018-06-29 07:47
@sebavan Glad to see there is a progress on what you were busy with.

Is this how it intended to be rendered?

<img width="795" alt="screen shot 2018-06-29 at 9 41 59 am" src="https://user-images.githubusercontent.com/810671/42079890-3f423c10-7b81-11e8-8f68-b8a814cc3c9f.png">

Then it is not what I was trying to achieve. Green one should overlap glow under it, not having a glow around.

**Comment by sebavan** [comment] 2018-06-29 16:05
Nope but the nightly has not been deployed yet :-) It will after deploy

**Comment by deltakosh** [comment] 2018-06-29 16:10
Should be good now :)
https://playground.babylonjs.com/#KTR4V2#1

**Comment by PixelsCommander** [comment] 2018-07-02 08:29
Confirm, works as expected. Thanks a lot!!

**Comment by PixelsCommander** [comment] 2018-07-10 12:46
After applying the solution we got chips to be rendered on top of the scene so had to roll it back. Any ideas on how to prevent this behavior?

<img width="788" alt="screen shot 2018-07-10 at 2 43 06 pm" src="https://user-images.githubusercontent.com/810671/42510683-f640e552-844f-11e8-9f0f-bbe412ea6419.png">

**Comment by sebavan** [comment] 2018-07-10 15:34
Hello,

This is the function doing the trick:

```
scene.setRenderingAutoClearDepthStencil(1, false, false, false);
```
This prevent the depth buffer to be cleaned before rendering the group 1. You should replace 1 by the group id of your chips.

**Comment by PixelsCommander** [comment] 2018-07-11 12:33
Once we have renderingGroupId = 0 on HighlightLayer shadows are lost on cards which do not have renderingGroup set.

I tried to set it a group but this was just guessing so not that much efficient.

**Comment by deltakosh** [comment] 2018-07-11 12:42
Rendering groups can be seen as layers. It is a good way to have different passes.

Can you repro in the playground a simple setup that looks like your game and we can help you define the correct rendering groups

**Comment by PixelsCommander** [comment] 2018-07-11 13:35
Huh, now we are confused. Not able to reproduce this in the playground. And no clue what it is so far, investigating. 

http://playground.babylonjs.com/#6T9SI9

**Comment by deltakosh** [comment] 2018-07-11 13:36
This is a good news if you think about it ;)

**Comment by PixelsCommander** [comment] 2018-07-11 15:43
Here is a playground http://playground.babylonjs.com/#6T9SI9#1

Bug(?) is caused by ```generator.usePercentageCloserFiltering = true;```

The similar one is reproducible in a demo here http://www.babylonjs-playground.com/#R1EVD0#3 but this time with another property of shadowGenerator.useBlurExponentialShadowMap = true; and no rendering groups.

**Comment by sebavan** [comment] 2018-07-11 16:11
I have moved the conversation to a new issue as the issue is not related to the EffectLayer.
