### ISSUE TITLE
Post process on one one camera effects both cameras 

### ISSUE THREAD

**Issue by stefanvanherwijnen** [BabylonJS/Babylon.js#9038] opened 2020-09-26 10:07 UTC
https://playground.babylonjs.com/#ZDXUBD

In the example above the left camera does not change (because the exposure is 1.0),  however the right camera has become much darker and the colors are different.
The same thing happens when other post processing is applied, such as contrast or blur. The post process works, but the unaffected camera is affected by something else.

https://forum.babylonjs.com/t/xr-post-process-on-one-camera-effects-both-cameras/14451

My guess is that some side effect of the post processing effects the parent camera, but I haven't been able to figure out exactly what is happening.

**Comment by Popov72** [comment] 2020-09-26 12:49
As stated in the template: **Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!**

Please, create a thread in the [forum](https://forum.babylonjs.com/) about this.

**Comment by RaananW** [comment] 2020-09-29 09:06
This is actually not an XR issue:

https://playground.babylonjs.com/#ZDXUBD#3

This happens whenever you attach a post process on the camera that is currently not active.

**Comment by RaananW** [comment] 2020-09-29 12:15
So, the issue is the global image processing configuration that we have the affects all cameras. So this is by design. (thanks @sebavan :-) )

To solve this you can do one of the two - either provide a different configuration when constructing the post process - https://playground.babylonjs.com/#ZDXUBD#6 , or apply the post process on both cameras.

I am closing this, please reopen if it still doesn't work after applying the solution.

**Comment by stefanvanherwijnen** [comment] 2020-09-29 13:32
I did notice that applying it to both cameras worked fine, but the thing is that I only want to effect one camera.
Changing the configuration indeed fixes it:
https://playground.babylonjs.com/#ZDXUBD#7

Thanks for the help and luckily it's just a configuration issue :smile:

**Comment by RaananW** [comment] 2020-10-07 09:44
Reopening issue.

Playground - https://playground.babylonjs.com/#ZDXUBD#18 works well with two cameras in the browser, but fails when used in XR (tested on desktop using an MR device). Reason might be that the effect is not using the camera's `outputRenderTarget`. Investigating further.

**Comment by RaananW** [comment] 2020-10-07 10:43
For logging reasons - the reason this playground didn't render correctly is that the output texture (set when calling `_finalizeFrame`) was ignoring the renderOutputTexture of the XR camera. 

The initial issue was the global image processing configuration, so it wasn't XR related. After further inspection (and thanks @stefanvanherwijnen for being persistent!!) it seems like it is (mainly) an XR issue, as it is related to (sub)cameras with renderoutput texture defined.

After the fix the following playground should be expected to work:

https://playground.babylonjs.com/#ZDXUBD#22

**Closed** 2020-10-07 18:16 UTC
Labels: VR/AR/XR, bug
