### ISSUE TITLE
Organization/Cleanup: Change functions organized into static classes to regular functions, Object-like classes into objects

### ISSUE THREAD

**Issue by dr-vortex** [BabylonJS/Babylon.js#14805] opened 2024-02-21 23:26 UTC
*Note: Examples do not include comments and use only signatures for brevity.*

Several classes are used only as a container for a collection of functions. These functions do not use class instances, nor do they use each other in any way that would require a class. This leads to unneeded repetition, and potentially has performance impacts. Moreover, using a functional approach instead of an OOP approach supports tree shaking and ESM better (#12593)

One good example is `Scalar`, which could be rewritten as:
```ts
export const TwoPi: number = Math.PI * 2;
export function withinEpsilon(a: number, b: number, epsilon: number = 1.401298e-45): boolean;
export function toHex(i: number): string;
export function sign(value: number): number ;
export function clamp(value: number, min = 0, max = 1): number;
export function ilog2(value: number): number ;
export function repeat(value: number, length: number): number;
export function normalize(value: number, min: number, max: number): number;
export function denormalize(normalized: number, min: number, max: number): number;
export function deltaAngle(current: number, target: number): number;
export function pingPong(tx: number, length: number): number;
export function smoothStep(from: number, to: number, tx: number): number;
export function moveTowards(current: number, target: number, maxDelta: number): number;
export function moveTowardsAngle(current: number, target: number, maxDelta: number): number;
export function lerp(start: number, end: number, amount: number): number;
export function lerpAngle(start: number, end: number, amount: number): number;
export function inverseLerp(a: number, b: number, value: number): number;
export function hermite(value1: number, tangent1: number, value2: number, tangent2: number, amount: number): number;
export function hermite1stDerivative(value1: number, tangent1: number, value2: number, tangent2: number, time: number): number;
export function randomRange(min: number, max: number): number;
export function rangeToPercent(number: number, min: number, max: number): number;
export function percentToRange(percent: number, min: number, max: number): number;
export function normalizeRadians(angle: number): number;
export function hcf(a: number, b: number): number;
```

There are numerous examples though. Here are all of the classes like this I could find:

**Core (packages/dev/core/src):**
- `CompatibilityOptions` (Compat/compatibilityOptions.ts)
- `DeviceEventFactory` (DeviceInput/eventFactory.ts)
- `ShaderProcessor` (Engines/Processors/shaderProcessor.ts)
- `WebGPUTextureHelper` (Engines/WebGPU/webgpuTextureHelper.ts)
- `Constants` (Engines/constants.ts) [<sup>enum</sup>](#user-content-fn-enum)
- `EngineFactory` (Engines/engineFactory.ts)
- `EngineStore` (Engines/engineStore.ts)
- `PerformanceConfigurator` (Engines/performanceConfigurator.ts)
- `ShaderStore` (Engines/shaderStore.ts)
- `ClipboardEventTypes` (Events/clipboardEvents.ts) [<sup>enum</sup>](#user-content-fn-enum)
- `EventConstants` (Events/deviceInputEvents.ts) [<sup>enum</sup>](#user-content-fn-enum)
- `KeyboardEventTypes` (Events/keyboardEvents.ts) [<sup>enum</sup>](#user-content-fn-enum)
- `PointerEventTypes` (Events/pointerEvents.ts) [<sup>enum</sup>](#user-content-fn-enum)
- `LightConstants` (Lights/lightConstants.ts) [<sup>enum</sup>](#user-content-fn-enum)
- `SceneLoader` (Loading/sceneLoader.ts)
- `SceneLoaderFlags` (Loading/sceneLoaderFlags.ts)
- `GreasedLineMaterialDefaults` (Materials/GreasedLine/greasedLineMaterialDefaults.ts)
- `MaterialFlags` (Materials/materialFlags.ts)
- `MaterialHelper` (Materials/materialHelper.ts)
- `Axis` (Maths/math.axis.ts)
- `Frustum` (Maths/math.frustrum.ts)
- `BezierCurve` (Maths/math.path.ts)
- `Angle`[*](#user-content-rewrite-minor) (Math/math.path.ts)
- `Scalar` (Maths/math.scalar.ts)
- `Polygon` (Meshes/polygonMesh.ts)
- `CubeMapToSphericalPolynomialTools` (Misc/HighDynamicRange/cubemapToSphericalPolynomial.ts)
- `HDRTools` (Misc/HighDynamicRange/hdr.ts)
- `PanoramaToCubeMapTools` (Misc/HighDynamicRange/panoramaToCubemap.ts)
- `PerfCollectionStrategy` (Misc/PerformanceViewer/performanceViewerCollectionStrategies.ts)
- `AndOrNotEvaluator` (Misc/andOrNotEvaluator.ts)
- `ArrayTools` (Misc/arrayTools.ts)
- `DataStorage` (Misc/dataStorage.ts)
- `DDSTools` (Misc/dds.ts)
- `SerializationHelper` (Misc/decorators.ts)
- `DeepCopier` (Misc/deepCopier.ts)
- `DumpTools` (Misc/dumpTools.ts)
- `FilesInputStore` (Misc/filesInputStore.ts)
- `GradientHelper` (Misc/gradients.ts)
- `GreasedLineTools` (Misc/greasedLineTools.ts)
- `InstantiationTools` (Misc/instantiationTools.ts)
- `Logger` (Misc/logger.ts)
- `PivotTools` (Misc/pivotTools.ts)
- `PrecisionDate` (Misc/precisionDate.ts)
- `RetryStrategy` (Misc/retryStrategy.ts)
- `RGBDTextureTools` (Misc/rgbdTextureTools.ts)
- `SceneSerializer` (Misc/sceneSerializer.ts)
- `Tags` (Misc/tags.ts)
- `TimingTools` (Misc/timingTools.ts)
- `Tools` (Misc/tools.ts)
- `UniqueIdGenerator` (Misc/uniqueIdGenerator.ts)
- `ParticleHelper` (Particles/particleHelper.ts)
- `HelperTools` (Physics/physicsHelper.ts)
- `WebXRFeatureName` (XR/webXRFeaturesManager.ts)
- `SceneComponentConstants` (sceneComponent.ts)

**Core Tests  (packages/dev/core/test):**
- `AudioTestHelper` (unit/Audio/helpers/audioTestHelper.ts)
- `AudioTestSamples` (unit/Audio/helpers/audioTestSamples.ts)

**GUI (packages/dev/gui):**
- `MathTools` (src/2D/math2D.ts)

**Inspector (packages/dev/inspector)**
- `Inspector` (src/inspector.ts)
- `TextureHelper` (src/textureHelper.ts)
- `Tools` (src/tools.ts)

**Loaders (packages/dev/loaders):**
- `GLTFLoaderBase` (src/glTF/1.0/glTFLoader.ts)
- `GLTFUtils` (src/glTF/1.0/glTFLoaderUtils.ts)
- `ArrayItem` (src/glTF/2.0/glTFLoader.ts)
- `GLTFValidation` (src/glTF/glTFValidation.ts)

**Serializers (packages/dev/serializers/src):**
- `_GLTFAnimation` (glTF/2.0/glTFAnimation.ts)
- `GLTF2Export` (glTF/2.0/glTFSerializer.ts)
- `_GLTFUtilities` (glTF/2.0/glTFUtilities.ts)
- `OBJExport` (OBJ/objSerializer.ts)
- `STLExport` (stl/stlSerializer.ts)

**Shared UI Components (packages/dev/sharedUiComponents/src):**
- `Popup` (lines/popup.ts)
- `StringTools` (stringTools.ts)
- `DisplayLedger` (nodeGraphSystem/displayLedger.ts)
- `NodeLedger` (nodeGraphSystem/nodeLedger.ts)
- `PropertyLedger` (nodeGraphSystem/propertyLedger.ts)
- `TypeLedger` (nodeGraphSystem/typeLedger.ts)

**Tools (packages/tools):**
- `GUINodeTools` (guiEditor/src/guiNodeTools.ts)
- `Tools` (guiEditor/src/tools.ts)
- `Transcoder` (ktx2Decoder/src/transcoder.ts)
- `BlockTools` (nodeEditor/src/blockTools.ts)
- `SerializationTools` /nodeEditor/src/serializationTools.ts)
- `Popup` (nodeEditor/src/sharedComponents/popup.tsx)
- `BlockTools` (nodeGeometryEditor/src/blockTools.ts)
- `SerializationTools` (nodeGeometryEditor/src/serializationTools.ts)
- `Popup` (nodeGeometryEditor/src/sharedComponents/popup.tsx)
- `EnvironmentTools` (sandbox/src/tools/environmentTools.ts)
- `LocalStorageHelper` (sandbox/src/tools/localStorageHelper.ts)

<a href="#user-content-rewrite-minor" id="rewrite-minor">*</a> Would require minor rewriting (e.g. a single value is manipulated)
<a href="#user-content-fn-enum" id="fn-enum"><sup>enum</sup></a> Would work better as an `enum` (or `const enum`)

This is a regular expression which matches any class that contains only static members, that I found very useful:
```regex
(class|implements)\s+\w+\s*\{\n?\s*((public|private|protected)?\sstatic\s+\w+\s*(\(.*\))?\s*(:\s+\w+\s*)?(\{(.|\n)*\}|(=.*))?\s*;?\n*)+\s*\}
```

**Comment by RaananW** [comment] 2024-02-22 19:02
Thanks a lot for the list!
This is correct. We are fully aware of that and are working on fixing it across the framework. work has begun with internal function containers (like the FileTools), and we will eventually move the rest.
There are some consequences to changing the architecture, and we want to be sure that everything works as we expect it to work.
I am closing this for now, as this is a duplicate of an internal team issue we are tracking.

Thanks again!

**Closed by RaananW** 2024-02-22 19:02 UTC

**Comment by dr-vortex** [comment] 2024-02-22 21:45
@RaananW,

I'm interested in helping and would be willing to submit a PR. Is there any way I can help?

**Comment by RaananW** [comment] 2024-02-26 11:25
I will keep you updated

**Comment by dr-vortex** [comment] 2024-02-26 12:01
Thanks!

**Comment by Technorocker** [comment] 2024-10-14 21:18
I apologize for hijacking but I've spent the last 30 min searching the web to understand where or how to use Lerp from the Scalar class now. Soon as I try to use it I see the deprecated line and tooltip, It says use scalar.functions but I can't find any reference to where or what that means. 

I'm taking a course to learn babylonjs so I'm sorry for my noobness here.

**Comment by james-pre** [comment] 2024-10-14 21:50
> The autocomplete, or maybe the intellisense doesn't show the option to import it, I had to go search inside the node_modules to the folder location to see what the actual file was called.

This may be because the ESM functions are not exported from https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Maths/index.ts?

**Comment by deltakosh** [comment] 2024-10-14 22:33
cc @RaananW
