### ISSUE TITLE
Incorrect lights direction when exported to glb 0, 1 or 2 times

### ISSUE THREAD

**Issue by noalak** [BabylonJS/Babylon.js#7377] opened 2019-12-30 16:44 UTC
Primary playground is [#KX53VK#30](https://www.babylonjs-playground.com/#KX53VK#30) testing right handed export to glb.
All bugs could be related, so I grouped them here.

### Black triangles
**Bug repro:** https://www.babylonjs-playground.com/#9DXCHP#1
**Expected result:** Triangles should be colored
**Current result:** When scene is exported and imported once (not twice), the triangles are black (unlighted).
**Comments:**
The light direction is back to front (0,0,-1).
When imported into the sandbox, the triangles are visible due to a default ambient light. The directional light is still back to front and the gizmo toggle has no effect on light direction. Those behaviors in the sandbox are as expected.

### Light direction
**Bug repro:** https://www.babylonjs-playground.com/#KX53VK#30
**Expected result:** The light should be oriented as initially front to back (0,0,1).
**Current result:** When scene is exported and imported twice (unmodified playground), the light direction is reversed: oriented back to front (0,0,-1).
**Comments:**
The gizmo toggle has no effect on light direction (unlike other 2 bugs above).
Triangles are lighted correctly, despite light direction being reversed.

### Linked light dummies
**Bug repro:** https://www.babylonjs-playground.com/#KX53VK#30
**Expected result:** Each _Light_ dummy should be independant from each other
**Current result:** the 2 _Light_ dummies, parent of the actual directional light, are someway linked together. Transform edition of one dummy through Inspector impacts the other. Comparing world matrix using the console.

I'm off the office until Monday 6th.
Adding @Jaskar for any question meanwhile.

**Comment by deltakosh** [comment] 2019-12-31 15:48
Adding @thomlucc to track them

@noalak @Jaskar can you guys work on it?

**Comment by Drigax** [comment] 2020-01-09 23:17
Linking
https://github.com/BabylonJS/Exporters/issues/696

As my test process touches on the light gizmo not aligning with the light's actual orientation

**Comment by Drigax** [comment] 2020-01-10 00:35
Few initial takeaways:
I'll start by figuring out why the gizmo is improperly oriented/modifies the light orientation on activation in a Right-Handed coordinate space. This seems key to being able to properly visually debug the other elements.

I'd assume that we're just improperly flipping the light direction when exporting the scene. This seems similar to our double root issues addressed via #7257 where we're converting our already converted light transform, but I'll have to look closer into the source to confirm.

@noalak for the linked light dummy issue, you linked to the original PG:
https://www.babylonjs-playground.com/#KX53VK#30
Is this correct? This scene appears to only contain a single light. Also I'm not sure what "light dummy" means in this context, can you please clarify?

Thanks

**Comment by noalak** [comment] 2020-01-10 09:35
![2020-01-10_10h19_42](https://user-images.githubusercontent.com/20560340/72141225-bac5fa00-3392-11ea-8624-e76eaead170b.png)

The light dummies are the light meshes parenting the actual light. They are used as Transform nodes when importing a glTF light.
If you edit in the Inspector the rotation of the node selected in the image above, and then select its parent, the displayed rotation is affected as well.
World matrices of light dummies seem right (the parent world matrix is unchanged). The bug is probably on the Inspector refresh.

**Comment by noalak** [comment] 2020-01-22 14:59
Do you have all the informations you need to fix those bugs ?

**Comment by Drigax** [comment] 2020-02-06 03:15
Thanks @noalak, I think I have all I need to make progress on this.

I'm moving the gizmo related issue to a separate bug: #7603 as It's not really related to these issues, just a very annoying occurance when trying to reproduce this.

**Comment by Drigax** [comment] 2020-02-06 03:43
In investigating the light export issue, I am noticing some strange behavior of the lights when we use a right handed coordinate system:

I am using [#KX53VK#32](https://www.babylonjs-playground.com/#KX53VK#32) to reproduce this (using my #7603 fix). When I use a right handed coordinate system:

**Comment by CedricGuillemet** [comment] 2020-02-06 09:51
The triangle is black because the face winding doesn't correspond to the normal.
I think this happens because you have 2 swaps in your PG.
- one with the positions depending on RH/LH
- one with the ComputeNormals
The 1st swap will make the normal flipped (because of the position), then you flip again the normal with the ComputeNormals call.
As the positions correspond to what you want, you don't need to flip the normals a second time.

https://www.babylonjs-playground.com/#KX53VK#33

**Comment by Drigax** [comment] 2020-02-06 19:28
Ok, the test scene appears to work now, I'm very concerned about the vertex normals in our right handed system now (see https://www.babylonjs-playground.com/#KX53VK#34) :

![image](https://user-images.githubusercontent.com/3952729/73971160-3bfda780-48d3-11ea-9f1b-369ac2e41a33.png)

If we use the vertex normal gizmo, it shows the normals as pointing backwards from the plane? This doesn't seem right either, the generated plane in scene seems generated with proper normal orientation and winding order, but is also lit backwards:
![image](https://user-images.githubusercontent.com/3952729/73971340-8e3ec880-48d3-11ea-8a89-6014fc98ddb5.png)
![image](https://user-images.githubusercontent.com/3952729/73971392-a3b3f280-48d3-11ea-8e0c-e433e25cd700.png)

I'm starting to suspect that we're lighting our scene wrong in right handed mode...

**Comment by Drigax** [comment] 2020-02-06 22:33
After talking with @CedricGuillemet , he pointed me to this thread which prompted the original change to the vLightSpecular direction:
https://forum.babylonjs.com/t/solved-unexpected-light-gizmo-on-right-hand-system/5043/15

This looks eerily similar to the change I just addressed via #7603, looks like we conflated a lighting error with the gizmo error. I believe that it's for the best to fix this, as we can reproduce this regression by modifying this testing scene:
https://www.babylonjs-playground.com/#0YYQ3N#0
![image](https://user-images.githubusercontent.com/3952729/73984131-d28a9280-48ec-11ea-931a-4da3beba9e3a.png)
by changing the scene handedness before import:
![image](https://user-images.githubusercontent.com/3952729/73984175-ecc47080-48ec-11ea-94b4-c0c6789a5cac.png)

Which causes our poor cat to be eerily lit. Undoing commit https://github.com/BabylonJS/Babylon.js/pull/6712/files/8dcdbf7386243e7acdededa6d8b8ecde436d1b4c#r313200449 appears to fix this regression in combination with the previously mentioned gizmo fix:
![image](https://user-images.githubusercontent.com/3952729/73984490-99065700-48ed-11ea-99a4-6529ba22b518.png)

**Comment by Drigax** [comment] 2020-02-06 23:19
Now this causes our original test scene: https://www.babylonjs-playground.com/#KX53VK#30
To fail on validation.  I believe that we originally did not have proper light orientation, as the directional light instantiated in scene was facing (0,0,1) regardless of handedness. I think this one slid through the cracks and our original test scene was not properly constructed.

I will update this testing scene to work correctly as a part of the light direction reverting PR; the lights should face our triangles regardless of scene handedness. The unit tests will be updated to reference:
https://www.babylonjs-playground.com/#KX53VK#35 (Left handed)
https://www.babylonjs-playground.com/#KX53VK#36 (right handed)

**Comment by bghgary** [comment] 2020-02-06 23:24
It would be good to verify that the [double root issue](https://github.com/BabylonJS/Babylon.js/issues/6349) is also fixed once ready.

**Comment by Drigax** [comment] 2020-02-14 10:36
Regarding the light orientation issue, there are multiple issues happening here:

For one, our lights aren't being properly exported from a right handed scene, they are 180degY off, as the exported node should be oriented such that the light shines towards -Z:

![image](https://user-images.githubusercontent.com/3952729/74522382-eb3c0f00-4ecf-11ea-8426-0a0e1ce29550.png)

This appears to be caused by using the same calculation for the light's yaw angle given the direction, a right handed system should invert the input direction Z axis to align with the coordinate system:

https://github.com/BabylonJS/Babylon.js/blob/768c2b07c9426f5beb6f6138005d665ae8419a31/serializers/src/glTF/2.0/Extensions/KHR_lights_punctual.ts#L109

In addition, the light direction is toggled, due to a duplication of light dummy nodes. On import, we create a dummy node oriented such that the light has a direction of (0,0,-1) regardless of scene handedness. On export, we preserve that node, and export that dummy node with the light parented to that node as a new node containing the KHR_lights_punctual extension. This node then duplicated on the next import, causing the light to flip direction.

![image](https://user-images.githubusercontent.com/3952729/74523441-ea0be180-4ed1-11ea-9ba8-73f36cc9707e.png)

In order to fix this issue, I had to make some alterations to the _applyExtension contract (and affected methods and interfaces that use this contract)

Originally, there was no capability to use or return a null value from an export extension handler method, my changes intended to expand the contract to allow for an extension to "void" an exported null in this case where we don't want to duplicate an existing exported node. From there, all that's needed is to reorient the exported grandparent node of the light to encapsulate the light.

**Closed** 2020-02-14 16:21 UTC
Labels: bug, exporters, in progress
