### ISSUE TITLE
Mesh split doesn't work in Blender

### ISSUE THREAD

**Issue by jackcaron** [BabylonJS/Babylon.js#631] opened 2015-07-21 17:53 UTC
Here's an example scene: https://www.dropbox.com/s/1z5hgh4xrmrekjx/sibenik-cathedral-vray.blend?dl=0

When I export this with Blender, only a part of the mesh is showing. So in the Blender exporter, I increase the value of *MAX_VERTEX_ELEMENTS* to *16777216* and after the export, the whole mesh is showing up properly in Babylon.js.

There's a bug the way the mesh is split. And when I put *MAX_VERTEX_ELEMENTS* to smaller values, a smaller part of the mesh was showing and the others were ignored.

**Comment by deltakosh** [comment] 2015-07-21 18:25
Can you submit a PR to update the MAX-VERTEX-ELEMENTS in the exporter?

**Comment by bhouston** [comment] 2015-07-21 18:35
@deltakosh, be aware that updating MAX_VERTEX_ELEMENTS is problematic because by default WebGL only supports 16 bit index buffers, which means that they can only handle 65535 vertex indices max.

If we increase MAX_VERTEX_ELEMENTS, it means that the WebGL Extension [OES_element_index_uint](https://www.khronos.org/registry/webgl/extensions/OES_element_index_uint/) has to be present.

Most devices support it, but there are a few exceptions:
- +95% of Windows Mobile devices do not support this extension.
- ~25% of Andriod devices do not support this extension.

We will submit this fix though.

**Comment by Palmer-JC** [comment] 2015-07-21 18:41
Maybe implement it as a checkbox on the exporter properties, maybe 'Allow 32bit indices' & a default of false?  Also, I tested this a while back using the same trick of lowering the limit and it worked at that time.  Do not know regression started occuring.

**Comment by deltakosh** [comment] 2015-07-21 19:06
Agree with the checkbox.. But I thought the mesh splitter was fixed by JCP sometimes ago

**Comment by deltakosh** [comment] 2015-07-21 19:47
@Palmer-JC: Do you mind checking the mesh splitter? Thank you so much!

**Comment by bhouston** [comment] 2015-07-21 19:49
Could it be something to do with mesh splitting being incompatible with multi-material meshes?  This particular Cathedral is one mesh with a lot of materials on it.

This line in the exporter looks suspicious to me - but I haven't traced through it:

https://github.com/BabylonJS/Babylon.js/blob/master/Exporters/Blender/io_export_babylon.py#L697

From my reading of the above line, it looks like it stops writing materials of a multi-material if there is a split mesh.

**Comment by deltakosh** [comment] 2015-07-21 20:03
That's right. I can remember now. We do not support mesh splitting when multimaterials are used. I suggest then exporting the mesh with 32bits on in this case and just emitting a warning

**Comment by deltakosh** [comment] 2015-07-21 20:05
And BTW, Babylon.js supports OES_element_index_uint so it won't be a problem as long as the device supports it. But because we will emit a warning that's not a problem

**Comment by Palmer-JC** [comment] 2015-07-21 20:15
I can add it into my release.  I have done a lot of re-factoring, and am now processing materials as meshes are processed for procedural texture baking purposes.

I have not taken into account baking for split meshes yet, but will.  Should not have to bake more than once.  

Is the checkbox still needed?

**Comment by deltakosh** [comment] 2015-07-21 20:23
Don't think so:)

**Comment by Palmer-JC** [comment] 2015-08-07 19:37
This is implemented as of exporter version 3.0

**Closed** 2015-08-07 19:51 UTC
Labels: bug
