### ISSUE TITLE
loading screen position bug

### ISSUE THREAD

**Issue by spirit-infernal** [BabylonJS/Babylon.js#4542] opened 2018-06-15 19:09 UTC
Hello everyone. 

--reproduction-
For reproduce bug you need to set up an angular project, add babylonjs / babylonjs viewer as dependency and include render canvas in one of the components as I done it. 
The problem is that loading screen placing beyond all angular components and have an incorrect position, but have a correct height and width, same as a canvas have.

-expected behaviour-
place loading screen div at correct place. probably right at the top of canvas element, not at the end of all DOM elements as it placing right now

-current result-
loading screen div placing at the end of all DOM elements, which causes wrong positioning. at least, when using babylonjs  as well as babylonjs viewer in angular projects.

**Comment by deltakosh** [comment] 2018-06-15 20:23
We really need a repro or a page where we can see it

**Comment by RaananW** [comment] 2018-06-17 22:27
The loader element in Babylon (core) is either absolute pairings or fixed positioned, and is add to the body. It would be best to have a project where it didn't work an we can work on the positioning.

Regarding the viewer - it is company contained in a single container. What version of the viewer have you tested?

**Comment by RaananW** [comment] 2018-06-20 13:02
bump - any chance of getting a test project? SO I can know your setup and understand what the problem is.

**Comment by deltakosh** [comment] 2018-06-22 23:44
I will close it for now
Please reopen it if there is an update

**Closed by deltakosh** 2018-06-22 23:44 UTC

**Comment by dtrinh100** [comment] 2018-10-26 02:40
I think I have a similar issue as this one. I have attached images to show the issue for a demo project that I am working on.

The loading screen:
![screenshot from 2018-10-25 22-30-26](https://user-images.githubusercontent.com/1930347/47541267-a806f880-d8a6-11e8-8992-1dec0e200bbd.png)

Notice the white space between the body of the canvas and the footer.

Once it's done loading, it works the way I wanted to as seen with the screenshot below:

![screenshot from 2018-10-25 22-31-05](https://user-images.githubusercontent.com/1930347/47541301-c8cf4e00-d8a6-11e8-8fe2-4552cbe0437f.png)

My ideal behavior of the loading screen would be having the loading screen take up the full height as the final screen. Let me know if you need source code, so you can reproduce it.

**Comment by deltakosh** [comment] 2018-10-26 13:53
Can you share a LIVE repro somewhere ?
