### ISSUE TITLE
babylonjs3->4 MeshBuilder.CreatePlane with Plane.FromPoints seems wrong

### ISSUE THREAD

**Issue by 0x53A** [BabylonJS/Babylon.js#7488] opened 2020-01-21 15:30 UTC
I noticed that my planes were rendered different after updating from 3.x to 4.1.

These are supposed to be horizontal.

old:
![image](https://user-images.githubusercontent.com/4236651/72817159-9ce97680-3c69-11ea-9400-765643dafdf1.png)

new:

![image](https://user-images.githubusercontent.com/4236651/72817190-a8d53880-3c69-11ea-8d39-03b807a6d6b1.png)

I tried creating a playground reproduction here: https://www.babylonjs-playground.com/#WSQPQW

```ts

        // ------------------------------------------------
        // Create three spheres
        
        var sphere1 = BABYLON.Mesh.CreateSphere("sphere1", 16, 1, scene); // sphere at center

        var sphere2 = BABYLON.Mesh.CreateSphere("sphere2", 16, 2, scene); // sphere at x=10
        sphere2.setAbsolutePosition(new BABYLON.Vector3(10, 0, 0));
        
        var sphere3 = BABYLON.Mesh.CreateSphere("sphere3", 16, 3, scene); // sphere at z=10
        sphere3.setAbsolutePosition(new BABYLON.Vector3(0, 0, 10));



        // ------------------------------------------------
        // Create Plane

        let plane = BABYLON.Plane.FromPoints(
            new BABYLON.Vector3(0, 0, 0),
            new BABYLON.Vector3(1, 0, 0),
            new BABYLON.Vector3(0, 0, 1));

        var planeMesh = BABYLON.MeshBuilder.CreatePlane("plane",
            {
                height: 10,
                width: 5,
                sourcePlane: plane,
                sideOrientation: BABYLON.Mesh.DOUBLESIDE
            },
            scene);

```

![image](https://user-images.githubusercontent.com/4236651/72817968-f7370700-3c6a-11ea-8d1b-2011346ee673.png)

1) Note how height and width are flipped
2) the plane is reversed, if you remove the doubleside it will be invisible from above.

This matches what I have observed in my own code.

**Comment by 0x53A** [comment] 2020-01-21 16:21
For now I have copy-pasted the original implementation into my own code:

```ts
    public static CreatePlane2(name: string, options: { size?: number, width?: number, height?: number, sideOrientation?: number, frontUVs?: BABYLON.Vector4, backUVs?: BABYLON.Vector4, updatable?: boolean, sourcePlane?: BABYLON.Plane }, scene: BABYLON.Scene): BABYLON.Mesh {
        var plane = new BABYLON.Mesh(name, scene);

        options.sideOrientation = Playground.updateSideOrientation(options.sideOrientation);
        plane._originalBuilderSideOrientation = options.sideOrientation;

        var vertexData = BABYLON.VertexData.CreatePlane(options);

        vertexData.applyToMesh(plane, options.updatable);

        if (options.sourcePlane) {
            plane.translate(options.sourcePlane.normal, options.sourcePlane.d);

            var product = Math.acos(BABYLON.Vector3.Dot(options.sourcePlane.normal, BABYLON.Axis.Z));
            var vectorProduct = BABYLON.Vector3.Cross(BABYLON.Axis.Z, options.sourcePlane.normal);

            if (vectorProduct.lengthSquared() > BABYLON.Epsilon) {
                plane.rotate(vectorProduct, product);
            }
        }

        return plane;
    }

    private static updateSideOrientation(orientation?: number): number {
        if (orientation == BABYLON.Mesh.DOUBLESIDE) {
            return BABYLON.Mesh.DOUBLESIDE;
        }

        if (orientation === undefined || orientation === null) {
            return BABYLON.Mesh.FRONTSIDE;
        }

        return orientation;
    }
```

**Comment by deltakosh** [comment] 2020-01-21 16:53
Yep this seems weird..Wondering why we changed it

Do you want to PR the change to make it correct?

**Comment by 0x53A** [comment] 2020-01-21 16:56
The change was made by these two PRs: https://github.com/BabylonJS/Babylon.js/pull/5500, https://github.com/BabylonJS/Babylon.js/pull/5522

I don't want to just revert them.

**Comment by deltakosh** [comment] 2020-01-21 17:34
Actually after checking it, it works as expected

The side is deduced from the winding order of your plane. To get it correctly you need to build your source plane in the other direction:
https://www.babylonjs-playground.com/#WSQPQW#1

Then we align the plane with your plane normal and this is where unfortunately there are several solutions. The system picks one but we have an infinity of possible values :(

AS long as you are unblocked I will close this issue as this is not a bug but more inherent to the way we align to the plane normal

**Closed by deltakosh** 2020-01-21 17:34 UTC

**Comment by 0x53A** [comment] 2020-01-21 18:21
Hi @deltakosh , thank you for the response. I am unblocked by reverting back to the apparently _wrong_ code, so I would like to understand it.

I still don't follow completely, would you mind checking it? School was a long time ago ...

Here is my understanding:

A plane is a mapping from 2D space (X/Y) to 3D space (X/Y/Z).

When I define a plane by three points A, B, C then the vector AB defines the X-Axis, the vector AC defines the Y-Axis. up is defined by the cross-product of AB x AC.

I found https://keisan.casio.com/exec/system/1223596129 and this confirms that ``Plane.FromPoints`` works this way, for my plane at the top I get ``d``=``0``, ``normal``=``(0,-1,0)`` in both.

Thus if I map a rectangle with width=5 and height=10 through this plane, where I assume than in 2D space width is the x-axis and height is the y-axis, I would expect it to be bigger on the x axis.

----------------------------

Note that even with your example (https://www.babylonjs-playground.com/#WSQPQW#1), width and height are "wrong", and I assume that if I placed a texture on the mesh, the texture would also be rotated:

![image](https://user-images.githubusercontent.com/4236651/72830235-94506a80-3c80-11ea-96ad-209d0bb9a1f9.png)

**Comment by 0x53A** [comment] 2020-01-21 18:41
hm, I think I got it.

It seems a plane does not have a _"rotation"_, both of these return the same plane with ``normal=(0/-1/0)``, ``d=0``:

```
C^                               ^ B
 |                               |
 |                               |
 |                               |
 |                               |
 +--------->             <-------+
 A         B             C        A

```

So the mapping from 2d space to 3d space is under-defined.

**Comment by deltakosh** [comment] 2020-01-21 18:58
exactly :) Right on the point ;D (So school was not that far)

**Comment by 0x53A** [comment] 2020-01-21 19:06
But with that context, I believe the original fix also does not really make sense, since a plane, apparently, does not have an inherent position and rotation

> Fix position and rotation of plane mesh
(https://github.com/BabylonJS/Babylon.js/pull/5500)

**Comment by 0x53A** [comment] 2020-01-21 19:25
But then ``MeshBuilder.CreatePlane`` with a ``sourcePlane`` is kinda useless, if it is not well defined.

I preferred the old behavior where it would align the 2D-X-Axis with the 3D-X-Axis and the 2D-Y-Axis with the 3D-Z-Axis for a horizontal plane. That seems (to me) to be the only reasonable behavior.

I guess I'll keep the old implementation I copy-pasted and think about it a little more.

Thank you!
