### ISSUE TITLE
WebXR in Valve Index using Firefox without Polyfil results low resolution and refresh rate

### ISSUE THREAD

**Issue by tlaukkan** [BabylonJS/Babylon.js#9079] opened 2020-10-03 08:48 UTC
**Repro**
Disabling the polyfil I could get the WebXR working with, firefox, firefox nightly and chrome canary.

- Expected result:
Good resolution and refresh rate with all browsers supporting WebXR.
- Current result:
 Chrome canary has good resolution and refresh rate but for some reason firefox and firefox nightly have low resolution (can see pixels very clearly) and slow refresh rate.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox, Firefox Nightly
 - Baybylonjs 4.2.0-beta.9

**Comment by deltakosh** [comment] 2020-10-04 16:05
hey as mentioned in the template please start a thread on the forum first

**Comment by deltakosh** [comment] 2020-10-04 16:52
Ok you just forgot to add the link actually: https://forum.babylonjs.com/t/webxr-in-htc-vive-using-windows-10-steamvr-firefox-and-polyfil/10430/10

**Comment by RaananW** [comment] 2020-10-05 11:48
I cannot reproduce this on any other device. I will need some more input (maybe screen-grabs if possible) of a scene like this:

https://www.babylonjs-playground.com/#JA1ND3#161

Will you be able to debug the scene and provide me some data? What I need is:

What is the value of this._options here - https://github.com/BabylonJS/Babylon.js/blob/master/src/XR/webXRManagedOutputCanvas.ts#L110

What is the serialized value of xrLayer here - https://github.com/BabylonJS/Babylon.js/blob/master/src/XR/webXRManagedOutputCanvas.ts#L157

**Comment by RaananW** [comment] 2020-10-09 07:47
I am closing this for now, please reopen if there is further input!

Thanks a lot!

**Closed by RaananW** 2020-10-09 07:47 UTC
Labels: VR/AR/XR, bug
