### ISSUE TITLE
Failure to compile type definition for ITextureAssetTask with TypeSript version 2.6.1

### ISSUE THREAD

**Issue by matthewtebbs** [BabylonJS/Babylon.js#3070] opened 2017-11-02 17:37 UTC
TypeScript **2.6.1**
BabylonJS **3.1.0-alpha3.6**

Fails at the BabylonJS module definition file _babylon.module.d.ts_.

```
(14862,15): error TS2430: Interface 'ITextureAssetTask' incorrectly extends interface 'IAssetTask'.
  Types of property 'onSuccess' are incompatible.
    Type '(task: ITextureAssetTask) => void' is not assignable to type '(task: IAssetTask) => void'.
      Types of parameters 'task' and 'task' are incompatible.
        Type 'IAssetTask' is not assignable to type 'ITextureAssetTask'.
          Property 'texture' is missing in type 'IAssetTask'.
```

Related to issue [#1508](https://github.com/BabylonJS/Babylon.js/pull/1508)?

**Comment by deltakosh** [comment] 2017-11-02 17:46
Correct. It should be fixed with next npm update (by end of this week)

Keeping this issue open for now

**Comment by matthewtebbs** [comment] 2017-11-02 17:46
Compiler options have strict = true.

**Comment by matthewtebbs** [comment] 2017-11-02 17:47
Great.

**Comment by RaananW** [comment] 2017-11-03 14:20
new npm alpha package was deployed yesterday. Was it fixed?

**Comment by matthewtebbs** [comment] 2017-11-03 17:53
Nope. I see babylon.module.d.ts with these lines still. Workaround is to run with non-strict type-checking in the client's _tsconfig.json_.

From _/src/Tools/babylon.assetsManager.ts_.
```typescript
interface ITextureAssetTask extends IAssetTask {
   onSuccess: (task: ITextureAssetTask) => void;
  onError: (task: ITextureAssetTask) => void;
  texture: Texture;
}
```

**Comment by deltakosh** [comment] 2017-11-03 17:56
I cannot reproduce :( Everything compiles here

**Comment by matthewtebbs** [comment] 2017-11-03 21:21
With strict type checking enabled? If you could attach your build commands against this project I'll try it on my end.

**Comment by deltakosh** [comment] 2017-11-03 23:15
I'll try to turn on strict mode first and keep you updated

**Comment by deltakosh** [comment] 2017-11-06 16:19
When I compile everything with these options:
`
    noResolve: false,
    target: 'ES5',
    declarationFiles: true,
    typescript: require('typescript'),
    experimentalDecorators: true,
    isolatedModules: false,
    noImplicitAny: true,
    noImplicitReturns: true,
    noImplicitThis: true,
    noUnusedLocals: true,
    strictNullChecks: true,
    strict: true
`

I have no issue :(

**Comment by deltakosh** [comment] 2017-11-06 16:37
Hum..Perhaps I can reproduce it actually
Which code do you use to trigger the problem?

**Comment by matthewtebbs** [comment] 2017-11-07 04:11
Created a reduced project at https://github.com/muddytummysoftware/ScratchPad.
After you've cloned this, in the ScratchPad project root,

> npm install
> npm start

```typescript
(15315,15): error TS2430: Interface 'ITextureAssetTask' incorrectly extends interface 'IAssetTask'.
  Types of property 'onSuccess' are incompatible.
    Type '(task: ITextureAssetTask) => void' is not assignable to type '(task: IAssetTask) => void'.
      Types of parameters 'task' and 'task' are incompatible.
        Type 'IAssetTask' is not assignable to type 'ITextureAssetTask'.
          Property 'texture' is missing in type 'IAssetTask'.
```

NodeJS **8.9.0**
Npm **5.5.1**
TypeScript **2.6.1**
BabylonJS **3.1.0-beta1.0**

**Comment by Kesshi** [comment] 2017-11-07 10:09
i foxed it here: https://github.com/BabylonJS/Babylon.js/pull/3093

**Comment by RaananW** [comment] 2017-11-09 11:20
I think this PR will sort things a bit more - https://github.com/BabylonJS/Babylon.js/pull/3112

**Closed** 2017-11-09 15:16 UTC
Labels: bug
