### ISSUE TITLE
Cannot read property 'Parse' of null

### ISSUE THREAD

**Issue by DrEight** [BabylonJS/Babylon.js#5478] opened 2018-11-07 17:42 UTC
Hello,
I just started to learn babylon and I'm confused because if I open the editor and click Scene->Download Scene and I drag the file in https://sandbox.babylonjs.com/ I receive the error in the tile.
(I'm talking about the default scene with 3 spheres ) 
So I tried to create a basic webapp and when I load the .babylon file I get the same exact error.

what am I doing wrong?

**Comment by deltakosh** [comment] 2018-11-07 17:48
Pinging @julien-moreau  who is the mastedmind behind the Editor

**Comment by julien-moreau** [comment] 2018-11-07 18:39
Hey @DrEight,
I tried to reproduce but I don't have the same errors. My errors are that I need the textures to load correctly (which is the wanted behavior because "Download Scene" just downloads the .babylon scene without the assets (textures, sounds, etc.)

Can you share me your .babylon file so I can try to understand what is going wrong? Thanks!

**Comment by DrEight** [comment] 2018-11-07 20:43
Attached there is the file. I would like to underline that I just loaded the editor and downloaded the scene.
Sorry for the basic question, but, what's the best method to download the scene with all the assets ?
Thank you

[Test.zip](https://github.com/BabylonJS/Babylon.js/files/2559084/Test.zip)

**Comment by julien-moreau** [comment] 2018-11-07 21:08
Okay just found the issue, you created a custom material using the Material Editor
To work properly you have to include the babylonjs-editor-extensions JS. Try to re-run the editor and export the scene again without adding custom assets like materials (from Material Editor) and post-processes (from Post-Process Editor)

**Comment by DrEight** [comment] 2018-11-08 15:21
Yes probably I created the custom material in a test that I did, but I reopened the browser window, so it seems strange that the editor keeps an old state. It is also strange that the viewer fails with a weird error if there is a custom material. I don't understand.
BTW I exported the scene, and I followed al the instructions in the readme.md, but the command 'npm run build' fails with a lot of : Cannot find module 'babylonjs-editor-extensions/extensions'
I googled a lot, but I can not find 'babylonjs-editor-extensions' and any documentation that it is talking about.
Can you help me ?

**Comment by julien-moreau** [comment] 2018-11-08 20:45
@DrEight thanks for reporting! Just noticed this problem!
I just fixed by making "babylonjs-editor" a npm module you'll be able to add in your project. I'll let you know once published with a new version of the editor

Once I publish the module, you'll be able to re-export your template and the "npm run build" will work fine
Writing to doc for this part ASAP

My answers:
- **It is also strange that the viewer fails with a weird error if there is a custom material**: not necessary stange because the babylonjs library is not intended to live-inject custom scripts for materials. It is an editor feature that you can use by adding the editor's lib (publishing ASAP) which works as an extension for babylonjs
- **so it seems strange that the editor keeps an old state**: what do you mean?

**Comment by DrEight** [comment] 2018-11-08 21:18
Never mind for 'keep the old state' I was not able to reproduce the problem, so it is probably a mistake.
Another bug in the editor that I found is: open the editor and 'Export Template'. Apart the 'babylon' format, every option return the error 'undefined'. Same happens if you 'Download the scene'

**Comment by deltakosh** [comment] 2018-11-09 14:49
Hello would you mind using the Editor repo (where the editor lives) for new issues regarding the editor?

https://github.com/BabylonJS/Editor

**Closed by deltakosh** 2018-11-09 14:49 UTC
Labels: question
