### ISSUE TITLE
glTF MSFT_screencoverage is nowhere to be found

### ISSUE THREAD

**Issue by xissburg** [BabylonJS/Babylon.js#6551] opened 2019-06-29 01:57 UTC
After maybe more than an hour trying to figure out why the LODs wouldn't shift I found that MSFT_screencoverage is not even accounted for. In fact, if you search for MSFT_screencoverage in the repo you'll get no results. I also couldn't find `addLODLevel` being called at any point.

This is a [sample glTF](https://gist.githubusercontent.com/xissburg/31cafc49261cdfbbf685fe687aa1a996/raw/21a4d9612683aa42f65c058c014445691873b17a/sphere_lod.gltf) you can load in the sandbox for testing. The change in triangle density should be visible when you zoom out, though, that doesn't happen.

@bghgary Mentioning you here since it seems you have implemented MSFT_lod in Babylon.js

**Comment by bghgary** [comment] 2019-07-01 19:32
MSFT_lod can be used either for progressive loading (i.e. loading from lowest LOD to highest LOD to improve first time to render) or for rendering (i.e. which LOD is rendered is based on some metric like distance or screen coverage). The implementation currently only has progressive loading.

There are two issues that cover this issue:
#4818
#5738

Closing this as a dupe of those two. Let me know if you have questions.

**Closed by bghgary** 2019-07-01 19:32 UTC
