### ISSUE TITLE
Obj does not map the textures correctly

### ISSUE THREAD

**Issue by menduz** [BabylonJS/Babylon.js#4686] opened 2018-07-05 18:45 UTC
Given result:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/260114/42341668-380c925e-806a-11e8-9e75-0a6a8349f3a9.png">

Expected result:
![image](https://user-images.githubusercontent.com/260114/42341683-4443eab8-806a-11e8-8261-15ffcb98467a.png)

You can test it here: https://sandbox.babylonjs.com/

Test asset: [crate.zip](https://github.com/BabylonJS/Babylon.js/files/2167822/crate.zip) (https://free3d.com/3d-model/crate-86737.html)

PS: Is there a way to upload files to the PG so I can create a PG repro?

**Comment by deltakosh** [comment] 2018-07-05 19:02
You can share your file on GitHub and then use rawgit.com to get a CORS compatible link
Also How about this? https://www.babylonjs-playground.com/#8INCIV#27

Duplicate of #4627

**Closed by deltakosh** 2018-07-05 19:02 UTC
