### ISSUE TITLE
error TS2307: Cannot find module 'babylonjs-gltf2interface/.js' or its corresponding type declarations.

### ISSUE THREAD

**Issue by gemron** [BabylonJS/Babylon.js#12330] opened 2022-04-02 11:25 UTC
**Use Github issues ONLY for validated bugs. PLEASE DISCUSS THEM ON THE FORUM FIRST!**

We have a really active forum to help answering questions (https://forum.babylonjs.com/)

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com):
- Expected result:
```
node_modules/@babylonjs/loaders/glTF/2.0/glTFLoader.d.ts:11:32 
import type * as GLTF2 from "babylonjs-gltf2interface";
```
- Current result:
```
 node_modules/@babylonjs/loaders/glTF/2.0/glTFLoader.d.ts:11:32 
 import type * as GLTF2 from "babylonjs-gltf2interface/.js";
```
**it's  suffix by "/.js"  ,so  error TS2307:Cannot find module 'babylonjs-gltf2interface/.js' or its corresponding type declarations.**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Version [e.g. 22] 5.0.2

**Smartphone (please complete the following information):**

**Additional context**
when i install 5.0.0-rc.13, this is  file  node_modules/@babylonjs/loaders/glTF/2.0/glTFLoader.d.ts:11:32 
is right,   import type * as GLTF2 from "babylonjs-gltf2interface";

**Comment by sebavan** [comment] 2022-04-04 15:00
This has been fixed and should be all good in 5.0.3

**Comment by sebavan** [comment] 2022-04-04 15:23
Actually I can confirm the issue since 5.0.1 https://forum.babylonjs.com/t/error-with-gltf-loader-module-in-recent-5-0-1-releases/29016/3

**Comment by RaananW** [comment] 2022-04-04 19:03
5.0.3 was just released and should be fine. Closing this bug, please reopen if there is any issue with it.

**Closed by RaananW** 2022-04-04 19:03 UTC
Labels: bug, build

**Comment by Dok11** [comment] 2022-07-09 19:55
Same error:
```
node_modules/@babylonjs/loaders/glTF/2.0/glTFLoaderInterfaces.d.ts:8:29 - error TS2307: Cannot find module 'babylonjs-gltf2interface' or its corresponding type d
eclarations.

8 import type * as GLTF2 from "babylonjs-gltf2interface";
```

package.json
```json
{
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/cdk": "^13.3.9",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@ngneat/until-destroy": "^9.0.0",
    "body-scroll-lock": "^4.0.0-beta.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "typed.js": "^2.0.12",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.3",
    "@angular/cli": "~13.2.3",
    "@angular/compiler-cli": "~13.2.0",
    "@babylonjs/core": "^5.14.1",
    "@babylonjs/loaders": "^5.14.1",
    "@types/body-scroll-lock": "^3.1.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "local-web-server": "^5.1.1",
    "typescript": "~4.5.2"
  }
}
```

Error when `import '@babylonjs/loaders/glTF/2.0/glTFLoader';` or `import '@babylonjs/loaders/glTF/2.0/Extensions/KHR_draco_mesh_compression';` is in my code.

**Comment by RaananW** [comment] 2022-07-11 13:25
Not the same error at all, this is because of a change we have made to peer-dependencies (vs. regular dependencies).
`babylonjs-gltf2interface` is a peer dependency of @babylonjs/loaders.
