### ISSUE TITLE
Android, xr HitTest bug

### ISSUE THREAD

**Issue by davidebaltieri31** [BabylonJS/Babylon.js#11761] opened 2021-02-23 16:55 UTC
I'm on Android. I've implemented an AR experience which draws detected planes and a 3d object on the hit test location. Continuously updated each frame.
I'm ciclying through the results of the onHitTestResultObservable similarly to this:
xrHitTestModule.onHitTestResultObservable.add((results) => {  
    for (var i = 0; i < results.length; i++) {
        BABYLON.Tools.Log("xrHitTestModule " + i + " " + results[i].position.x + " " + results[i].position.y + " " + results[i].position.z);
    }
...

When I hit multiple planes that are "overlapped" i get the same position for every result[i]. By overlapped I mean they are overlapped in the 2D view plane, but they are really 2 planes at different Z (height), like a table and the ground plane.
In this situation I get 2 hit but with the same position. 
When i hit the non overlapped parts I get 1 hit with the correct X/Y/Z position

On the C++ side in the function  Napi::Value GetHitTestResults(const Napi::CallbackInfo& info) of NativeXR.cpp
the line m_frame->GetHitTestResults(nativeHitResults, nativeRay, hitTestSource->GetEntityTypes());
correctly returns 2 hits with different positions.

**Comment by RaananW** [comment] 2022-02-16 11:45
Sorry for taking so long to answer. As previously written, this is not a bug but a "feature". What a developer sentence...

We can discuss whether or not the default behavior should be setting `autoCloneTransformation` to true. It will create a few vectors per frame that will be garbage collected if not used, but they are not too many.

Another solution is to clone every vector provided by the hit test, instead of referencing it directly. I leave this issue open for discussion.

**Comment by RaananW** [comment] 2022-07-22 14:24
I am closing this issue for now, but will be happy to continue the discussion (or re-open the issue) if needed.

**Closed by RaananW** 2022-07-22 14:24 UTC
Labels: VR/AR/XR
