### ISSUE TITLE
Cloning a glTF object with LOD remove its material

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#10171] opened 2021-04-09 23:22 UTC
This can be repro here: https://www.babylonjs-playground.com/#FHHM51#40

Whereas simple spheres are working fine: https://playground.babylonjs.com/#LUMDVM#2

**Comment by deltakosh** [comment] 2021-04-12 15:59
Adding @bghgary for the material issue
In a nutshell, the mesh clone is not getting the material. It is actually getting one but the LOD extension from gltf is somehow disposing it

**Comment by bghgary** [comment] 2021-04-12 21:50
This isn't exactly a bug.

The problem is that we are loading the LODs progressively. Cloning the object before the LODs are done loading means it will clone an intermediately LOD. The current behavior is that materials for intermediately LODs will be disposed when the final LOD is loaded.

It would be a difficult feature to implement if we want to be able to clone before the LODs are complete.

Here is how you would clone after the LODs are complete:
https://www.babylonjs-playground.com/#FHHM51#41

**Comment by deltakosh** [comment] 2021-04-12 22:08
I like when there is no bug :D
Closing the issue as we know how to deal with it

**Closed by deltakosh** 2021-04-12 22:08 UTC
Labels: bug, loaders
