### ISSUE TITLE
Zip downloaded from Playground no longer produces a runnable files

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Babylon.js#7926] opened 2020-03-27 09:41 UTC
Ref https://forum.babylonjs.com/t/problems-to-download-example-enabling-floor-meshes/9507/

It has been a long time since I downloaded code from the playground (PG). When I did you got a simple file consisting of the PG code wrapped in the [template](https://doc.babylonjs.com/babylon101/first#html-template). It now seems that you get all the PG code as well but without all the necessary files (or links) to run it.

From my point of view I would expect most users just want a simple working file(s) as it was before. If the intention is to create the full playground experience on zip download then more explanation is needed in the docs on how to run it and I would make this an option not a default.

**Comment by RaananW** [comment] 2020-03-27 15:50
A few notes:

1) the problem is the new /pg/CODE url structure. if you load this with the hashcode it downloads correctly. 
2) Even if downloaded correctly, there is a problem when the async keyword. is used. the `createScene()` call should be changed to:

```javascript
scene = createScene().then((scene) => {
  engine.runRenderLoop(function () {
    if (scene) {
      scene.render();
    }
  });
});
```

Will be fixed.

**Comment by BabylonJSGuide** [comment] 2020-03-27 16:00
👍

**Closed** 2020-03-27 18:53 UTC
Labels: Playground, bug
