### ISSUE TITLE
Canvas CachedMode with DesignSize has a different scale than non Cached mode

### ISSUE THREAD

**Issue by nockawa** [BabylonJS/Babylon.js#1940] opened 2017-03-28 06:50 UTC
http://www.babylonjs-playground.com/#22PLQU#0

Report to @wyklion

**Comment by abow** [comment] 2017-06-10 13:44
@deltakosh I can't reproduce this bug.  The only bug I see on that PG now is fixed by my latest PR.

**Comment by deltakosh** [comment] 2017-06-10 14:16
Closing then:)

**Closed by deltakosh** 2017-06-10 14:16 UTC
Labels: bug, canvas2d
