### ISSUE TITLE
GLTF: Should joint indices be decompressed to floats?

### ISSUE THREAD

**Issue by zeux** [BabylonJS/Babylon.js#6971] opened 2019-10-14 05:17 UTC
GLTF loader has the following code with a comment:

```js
// Load joint indices as a float array since the shaders expect float data but glTF uses unsigned byte/short.
// This prevents certain platforms (e.g. D3D) from having to convert the data to float on the fly.
else if (kind === VertexBuffer.MatricesIndicesKind) {
    accessor._babylonVertexBuffer = this._loadFloatAccessorAsync(`/accessors/${accessor.index}`, accessor).then((data) => {
```

This converts matrix indices unconditionally, even when they are using unsigned byte (which is the most common skinning format) - this doesn't match the performance advice mentioned here:

https://github.com/microsoft/angle/wiki/Getting-Good-Performance-From-ANGLE#--avoid-triggering-buffer-format-conversion

Additionally, the guidelines linked seem to suggest that one-time conversion (so presumably when the vertex data is stored in a static VBO) is not a cause for concern, and it's only relevant for 9.3 backend; right now the conversion is happening in JS which isn't optimal memory or performance wise.

Is there any more data as to why this change was done? I've tracked this down to the commit that introduced it but the commit message doesn't have any performance measurement and doesn't indicate a specific problem this is solving.

**Comment by bghgary** [comment] 2019-10-14 17:16
This is a tricky one.

First, a few notes:
- WebGL1 attributes can only take floating data. https://www.khronos.org/registry/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf (section 4.3.3)
- I don't know how accurate the document you referenced above. Microsoft's fork of the ANGLE project is fairly old now.

This fix is intended for [Babylon Native](https://github.com/BabylonJS/BabylonNative) which doesn't use ANGLE. ANGLE does the conversion internally. For WebGL1 (OpenGL ES 2.0), if the shader expects float data and integer data is provided, then it automatically converts integer data into float data (e.g. an integer of 1 is auto converted to 1.0f). In D3D, the same situation causes the integer of 1 to be casted directly to float data which ends up with garbage. I have found 0 documentation for this behavior and it took a while to figure this out as the graphics debuggers I've tried all report incorrect data when doing this with D3D.

That said, we probably can do something about this by using integer data for platforms/APIs that can do better including Babylon Native.

Is this causing a specific issue for you? I can investigate making this better.

**Comment by zeux** [comment] 2019-10-15 06:05
> WebGL1 attributes can only take floating data. https://www.khronos.org/registry/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf (section 4.3.3)

Note that this refers to GLSL inputs - the vertex attributes on the JS side (or C++ side for GLES) can use integer inputs via GL_BYTE/GL_UNSIGNED_BYTE/etc.

> In D3D, the same situation causes the integer of 1 to be casted directly to float data which ends up with garbage.

To me this suggests that the D3D implementation Babylon Native is using has a bug. WebGL 1 allows specifying integer attributes and they should be converted to floats automatically during rendering.

Note that the reason why ANGLE docs warn about this is that typically you'd expect the GPU to automatically handle this conversion at zero cost. However, when WebGL1 is implemented with Direct3D 9 class API behind the scenes (9.3 refers to feature level 9.3 for D3D10/11 APIs), the set of formats is restricted - the reference table is available here https://docs.microsoft.com/en-us/previous-versions/ff471324(v=vs.85); note that you *can* use 4-component unsigned byte, but short (2-byte per component) formats are restricted to signed formats. Because of this ANGLE has to do this conversion at buffer upload time - however, this is just for 9.3 hardware which isn't that popular.

> Is this causing a specific issue for you? I can investigate making this better.

The reason why I ask is that I've been studying GLTF loader from the point of view of decoding the input data; there are only two cases where input data is decoded into a float for vertex attributes - matrix indices and morph targets. Neither of these two seemed essential, and where for morph targets changing this requires somewhat deep changes - support for relative morphs and specifying morph data as vertex buffers instead of float arrays - the decoding of matrix indices seemed off.

**Comment by bghgary** [comment] 2019-10-15 16:41
> Note that this refers to GLSL inputs - the vertex attributes on the JS side (or C++ side for GLES) can use integer inputs via GL_BYTE/GL_UNSIGNED_BYTE/etc.

Right.

> To me this suggests that the D3D implementation Babylon Native is using has a bug.

This is certainly possibly. Babylon Native is relatively new. But we haven't found a good solution so far. Babylon Native doesn't use WebGL and doesn't use ANGLE anymore. For D3D, it now converts GLSL to HLSL via glslang and SPIRV-Cross. For the specific case of joint indices, this generates HLSL that expects float data. If I recall correctly, ANGLE did the same thing. In D3D, as far as I can tell, if the shader expects float data and the input data is non-normalized integer, it casts the data as float directly. I didn't find documentation for this. One possible way I can think of that might "fix" the issue is if the source GLSL shader is changed to expect integer input for joint indices. This will require some investigation.

> WebGL 1 allows specifying integer attributes and they should be converted to floats automatically during rendering.

Yes, agree. I would call Babylon's built-in shaders WebGL1 compatible and we do things sometimes to support other APIs/platforms. As we branch out into other platforms, including WebGPU and native platforms through Babylon Native, there will likely be more issues like this.

> I don't have a specific problem with this though - the conversions are extraneous and they make loading a bit slower, but it's not a high priority issue (and it's not a correctness issue).

Good to know, thanks! I agree doing this conversion on the JS side is not ideal and it would be great to remove it. Maybe we will find a good solution that works for all of our supported scenarios.

**Comment by zeux** [comment] 2019-10-16 03:52
I've tried to run Babylon Native without loading matrix indices as a float buffer, and indeed it doesn't work - the arrays aren't passed to the vertex array object. I'll take a look at why that is happening - this works fine in WebGL, so I'd expect it to work everywhere.

**Comment by zeux** [comment] 2019-10-16 04:04
... ah, bgfx doesn't support UInt16 and so Babylon Native doesn't either. Oh well. https://github.com/bkaradzic/bgfx/issues/739 tracks this but probably won't get the support for a while.

**Closed** 2019-10-16 04:33 UTC
Labels: discussion, glTF

**Comment by bghgary** [comment] 2019-10-16 22:34
> I think the right choice here is to work around this at the Babylon Native level - clearly non-normalized (or unsigned) attributes are not correctly supported by RecordVertexBuffer; I guess the only possible fix is to keep the data around and decode it on the C++ side

This is what ANGLE does as far as I can tell. I am a bit hesitate to say this is the right choice as Babylon Native isn't trying to support WebGL. But this is certainly an option and is something we've considered.

**Comment by zeux** [comment] 2019-10-17 01:00
Right now Babylon Native implementation special cases an odd subset of Babylon JS API - it's roughly "support types of data that valid GLTF files can produce through GLTF loader".

Because BabylonVertexBuffer is part of the public API, and provides support for FLOAT/SHORT/INT/normalized/etc. attributes, if Babylon Native has a goal of being able to run code that uses Babylon JS, it seems to me that Babylon Native has to support whatever BabylonVertexBuffer does - which is equivalent to WebGL.

The shader type confusion gets somewhat nuanced, not sure what exactly the contract here Babylon JS establishes between JS code and shader code.

**Comment by bghgary** [comment] 2019-10-17 16:30
> Right now Babylon Native implementation special cases an odd subset of Babylon JS API - it's roughly "support types of data that valid GLTF files can produce through GLTF loader".

It is true we are targeting loading glTF initially. The implementation will likely change a bit when we expand to more Babylon.js capabilities. I would not say Babylon Native implementation special cases anything specific to glTF though. We try not to do any processing as much as possible and in the case for joint indices, we've chosen to fix it in the glTF loader for now. The final implementation might be to fix it on the native side like you mentioned. I want to avoid it if there are better solutions.

> The shader type confusion gets somewhat nuanced, not sure what exactly the contract here Babylon JS establishes between JS code and shader code.

The contract between JS and shader is Babylon, not WebGL. The shaders have to work for WebGL1, WebGL2, WebGPU, and Babylon Native. This contract is not super clear yet.
