### ISSUE TITLE
[XR] Bug at value gripRay.origin when exiting/re-entering Immersive mode

### ISSUE THREAD

**Issue by polisena** [BabylonJS/Babylon.js#9210] opened 2020-10-20 11:02 UTC
When using WebXR, the instruction `controller.getWorldPointerRayToRef(gripRay, true)` gets the value of the coordinates of the controller. We print this value at each frame. Initially the values printed are correct, but when we exit and re-enter immersive mode the instruction prints an alternation of valid and invalid values.

**Repro**

- Bug repro on [Playground](https://www.babylonjs-playground.com/#EURMQW).

The following code is the core of the example:
```
const frameObserver = xrHelper.baseExperience.sessionManager.onXRFrameObservable.add(() => {
    if (motionController.handness === "right") {
        const gripRay = new BABYLON.Ray(new BABYLON.Vector3(), new BABYLON.Vector3());
        controller.getWorldPointerRayToRef(gripRay, true);
        console.log("gripRay.origin: " + gripRay.origin);
    }
});
```
That is, at each frame we print `gripRay.origin` for the right-hand controller. When I enter Immersive mode, the `gripRay.origin` is printed correctly:

![img1](https://user-images.githubusercontent.com/27902278/96577386-d6701080-12d3-11eb-812a-f180ef3bccb2.png)

But, when I press the Oculus button to exit Immersive mode, then press the Continue button to re-enter Immersive mode, two kind of values are printed in alternation: on the odd lines are printed the correct values for `gripRay.origin`, while on the even lines is printed the value of `gripRay.origin` at the moment we left Immersive mode the last time:

![img2](https://user-images.githubusercontent.com/27902278/96577423-e5ef5980-12d3-11eb-9a27-7ba0b0fb54d8.png)

The following image shows the moment in which we re-enter Immersive mode, which corresponds to the line at the center: we can see that at this line there is a circled "2", which corresponds to the same value printed twice: at the last frame when we exit immersive-vr and at the first frame when we re-enter immersive-vr:

![img3](https://user-images.githubusercontent.com/27902278/96577470-f4d60c00-12d3-11eb-8849-3ec840a9f443.png)

The following video shows how I reproduced the bug: first I enter the scene, placing the controller at the right, then press the Oculus button to exit immersive-vr, then move the controller at the left, and then re-enter immersive-vr:

[Video - How to reproduce the bug](https://ubercordes.com/permalink/babylonjs/01-issue-exit-enter-immersive-mode/how-to-reproduce-bug.mp4)

**Environment**
- Device: Oculus Quest
- Browser: Oculus Browser

**Comment by RaananW** [comment] 2020-10-27 08:39
So - after carefully  examining, testing, and understanding - this is not a bug but by design. 

The idea is this - observables will be triggered every time they event they are triggered by is fired. You have three observables defined:

onControllerAdded, onMotionControllInit, and onXRFrame . If you `add` an observer to them, it will be notified every time one of these conditions are met. It is the developers responsibility to clean up those observables if the user quit the session.

You can see how I solved it in the features manager:

https://github.com/BabylonJS/Babylon.js/blob/master/src/XR/features/WebXRAbstractFeature.ts#L69 - this will add an observer to the list of observers to be removed when detached (my definition of temporarily disposed). 

Out of the 3 observers registered, the one that is important to be removed is the frameObserver. Think about the frame observer as a onBeforeRender observer. You wouldn't add more than one, or will make sure to dispose it after it is not needed anymore.

The most sensible thing to do in this case is to use the onControllerRemoved observable and add a callback there to clear the frame observer when the controller was removed. This will be the cleanest and most efficient way of solving this - https://www.babylonjs-playground.com/#EURMQW#4

I am closing this for now, please comment here or reopen if you think it is still a bug.

**Closed by RaananW** 2020-10-27 08:39 UTC
Labels: VR/AR/XR
