### ISSUE TITLE
Loading Icon For Viewer Initially In The Corner

### ISSUE THREAD

**Issue by infosisio** [BabylonJS/Babylon.js#6643] opened 2019-07-30 06:25 UTC
As I have done all the common-sense customizations, I am fairly sure that this is a valid bug.

This is regarding the <babylon> (standalone) viewer, which every now and then once the page is loading, shows the loading icon at the top left corner of its parent div instead of at the center (until the loading is done).

I don't know if this has been reported before but I wanted to bring it to your attention as there is no reason it should be happening.

**Comment by sebavan** [comment] 2019-07-30 10:41
Hello, I can not repro unfortunately :-( Is it on all browsers ? and do you do anything special to repro ?

**Comment by RaananW** [comment] 2019-07-30 10:50
Hi @infosisio , could you share a demo or a webpage where it happens? Would be great to know how the container is being initializes and whether or not we can fully reproduce this and fix it.

**Comment by infosisio** [comment] 2019-07-30 13:09
@RaananW I figured out exactly what is happening. loading-screen width/height/color are set dynamically so sometimes the icon is rendered prior to those attributes being set. I hardcoded them and the issue is gone.

**Comment by sebavan** [comment] 2019-07-30 13:27
Nice catch, probably smthg we can address on our side then @RaananW  ?

**Comment by RaananW** [comment] 2019-07-30 13:39
Usin gthe default loader, the loading screen is set here - https://github.com/BabylonJS/Babylon.js/blob/master/Viewer/src/viewer/defaultViewer.ts#L589 . Right after the template is being rendered (synchronous), it takes the canvas size and forces the container to have it as width and height. Even if it wasn't synchronous, it would have taken max 1 frame to show. It is being set dynamically, because the canvas size can be changed. So each time the show function is executed, the size is configured. Of course you can use CSS (as you probably did) to force width and height.

What I can imagine is that sometimes the show function is throwing an exception, so that the code for width and height doesn't work. I assume that when it happens, the display is also not flex. If that's not the case, it might be that the canvas itself is dynamically changing?

Would still be great to see an example where it doesn't work, to understand what actually went wrong.

**Comment by infosisio** [comment] 2019-07-30 21:20
@RaananW I don't know what more I can supply for reproduction purposes, it just happens randomly, refreshing a lot of times in a row seems to spark it.

**Comment by RaananW** [comment] 2019-08-05 17:56
I'm constantly trying to reproduce this, but I sadly could get to a point when that happens. I'm closing the ticket for now, but will keep an eye on this and make sure to open this when it's reproducible.

For future contributors - please reply in this issue of you manage to reproduce the issue or if it happens to you too.

**Closed by RaananW** 2019-08-05 17:56 UTC
Labels: investigation, viewer
