### ISSUE TITLE
WebGPU Support

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Babylon.js#6443] opened 2019-06-04 14:35 UTC
Here is the work which will happen until the release regarding our the WebGPU support:

- [x] Shader Auto Upgrade:
    - [x] Create Processor
    - [x] Auto attribs upgrade
    - [x] Auto varyings upgrade
    - [x] Auto textures upgrade
    - [x] Auto uniforms upgrade
    - [x] Auto UBOs detection
    - [x] Binding Upgrades
    - [x] Manage UBO in vertex + fragment
    - [x] Manage Array in UBOs for bones
    - [x] Manage Array in UBOs for morph targets
- [x] Manage Texture Sampling Modes
- [x] Manage Blending
- [x] Handle Canvas Resizing
- [x] Update WebGPU.d.ts
- [x] GLB support
- [x] Fix Full Build
- [x] Playground support
  - [x] Merge in Master
- [x] Dynamic Materials -> Defines Changes
- [x] Texture Support without WebGL back-end
- [x] Mapped Buffers
- [x] Render target support
- [x] Post Process support
- [x] First Cleanup and TODO WEBGPU pass
- [x] Raw Textures
- [x] Dynamic Texture Sampler Setting -> Filtering and Wrapping
- [ ] Safari Preview Support (if shader choice has been made #6695)
- [x] **Compute Shader support**
- [x] Support all the left over states (clear, stencil, depth, culling...)
- [x] Transform feedback and Occlusion Queries
- [ ] Optimize uniform buffers and groups (dynamic buffer index)
- [ ] **Big Cleanup, tests, and docs**
- [X] Command buffer "Reuse-Like" mechanism
- [ ] Spector.js Support
- [x] Last Optimization phase
- [X] Optimize UBOs (like IBL/Scene and so on)
- [ ] ** Release \o/**

If you are interested to contribute one of them, no problem, I am all about sharing ;-)

**Comment by furcatomasz** [comment] 2019-08-05 06:29
is it (list) already up to date?

**Comment by sebavan** [comment] 2019-08-05 07:34
Yep, I am almost ready to post the shader conversion which will enable most of our webgl shaders to be compatible. As soon as it is done I will finally be able to create a playground for WebGPU.

**Comment by sebavan** [comment] 2019-08-06 01:04
It is definitely getting there despite a still growing list of todos:
![image](https://user-images.githubusercontent.com/16655165/62504008-f1ea1b00-b7f6-11e9-867b-580f9b90f2d4.png)

**Comment by sebavan** [comment] 2019-08-07 12:17
Playground for WebGPU (requires Chrome Canary with the flags turned on on MacOS)

https://playground.babylonjs.com/indexWebGPU.html

Lots of features are preventing a lot of PGs to run correctly but if you only use Mesh with materials and simple textures (jpg/png) it should be all good :-)

**Comment by davidworkman9** [comment] 2019-08-07 14:05
@sebavan any chance you'd be able to release a NPM version with this? I'd love to try it out in the context of my current project.

**Comment by sebavan** [comment] 2019-08-07 14:33
No, unfortunately, it is currently too early too release to npm. I plan to do it once I can merge in master after the WebGPU group decides what shader language that want to use :-)

You can nevertheless consume the file from the cdn : https://playground.babylonjs.com/js/babylonWebGpu.max.js

**Comment by sebavan** [comment] 2019-08-07 19:52
Custom shaders working back : https://www.google.com/url?q=https://www.babylonjs-playground.com/indexWebGPU.html%23XEU8N9%231&sa=D&source=hangouts&ust=1565293505988000&usg=AFQjCNF-IUbDmPdCtWVzQeuVjbdTMx2IcA

**Comment by sebavan** [comment] 2019-08-08 11:21
With now support for the inspector and the node Material with its awesome editor:
https://playground.babylonjs.com/indexWebGPU.html#TY9I71

**Comment by amornratmakto** [comment] 2019-08-22 07:47
Wow

**Comment by cx20** [comment] 2019-11-10 13:01
Since the specification of WebGPU has been changed recently, it seems that an error occurs when Playground is run on Canary version of Chrome.
https://github.com/gpuweb/gpuweb/commits/master/spec/index.bs
https://github.com/chromium/chromium/commits/master/third_party/blink/renderer/modules/webgpu

**Comment by sebavan** [comment] 2019-11-10 13:51
This is weird i fixed it on Thursday to adapt to latest setVertexBuffer. Are you on latest canary ?

**Comment by cx20** [comment] 2019-11-10 14:52
I tried the WebGPU sample and Babylon.js Playground with the following browser versions.

|browser      |version           |[WebGPU Samples](https://austineng.github.io/webgpu-samples/#rotatingCube)|[Babylon.js Playground WebGPU](https://playground.babylonjs.com/indexWebGPU.html)   |
|-------------|------------------|:------------------------------------------------------------------------:|:----------------------------------------------------------------------------------:|
|Chrome Canary|Chrome/80.0.3964.0|:white_check_mark:                                                        |:x:                                                                                 |
|Edge Canary  |Chrome/80.0.3956.0|:x:                                                                       |:white_check_mark:                                                                  |

WebGPU Samples seems to have been updated on 11/9.
https://github.com/austinEng/webgpu-samples/commits/master/src/examples

|old name    |new name   |
|------------|-----------|
|vertexInput |vertexState|
|stride      |arrayStride|
|attributeSet|attributes |

**Comment by sebavan** [comment] 2019-11-10 19:12
Ok i ll fix it tomorrow :-) thanks for the report

**Comment by sebavan** [comment] 2019-11-12 14:56
All fixed on Chrome Canary, we ll have to wait for Edge Canary to reach Chrome latest changes.

**Comment by cx20** [comment] 2019-11-14 12:45
Unfortunately, the latest version of Chrome Canary seems to have errors in [Babylon.js Playground](https://playground.babylonjs.com/indexWebGPU.html).

|browser      |version           |[WebGPU Samples](https://austineng.github.io/webgpu-samples/#rotatingCube)|[Babylon.js Playground WebGPU](https://playground.babylonjs.com/indexWebGPU.html)   |
|-------------|------------------|:------------------------------------------------------------------------:|:----------------------------------------------------------------------------------:|
|Chrome Canary|Chrome/80.0.3967.0|:white_check_mark:                                                        |:x:                                                                                 |
|Chrome Canary|Chrome/80.0.3966.0|:white_check_mark:                                                        |:white_check_mark:                                                                  |

```
BJS - [21:35:31]: Babylon.js v4.1.0-beta.2 - WebGPU engine
D3D12 closing pending command list failed with -2147467259
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
```

**Comment by deltakosh** [comment] 2019-11-14 15:09
cc @sebavan

**Comment by sebavan** [comment] 2019-11-14 16:24
It works for me 
![image](https://user-images.githubusercontent.com/16655165/68875571-59bbd600-0703-11ea-9266-6c7a9356e02a.png)

It might be only on your GC and is not (I do not think) related to Babylon directly. You might try to provide your info on a chromium bug report for Windows. Please also disable the skia composition in your chrome flags to run WebGPU on Windows at the moment.

**Comment by cx20** [comment] 2019-11-14 20:56
I tried both enable / disable skia composition settings, but the problem was not solved.
![image](https://user-images.githubusercontent.com/1833979/68893928-8dc9e200-0769-11ea-9292-c617da8a7790.png)
I am using ThinkPad X260's built-in GPU (Intel HD Graphics 520). I don't have any other environment to try, so I'll wait for a little more time for the new Chrome Canary.
I also reported the problem in the Chromium bug report.

**Comment by sebavan** [comment] 2019-11-18 17:59
Heads up as I will update the apis tomorrow due to a rename in the spec so you can expect Chrome canary to be ok tomorrow and it will probably take a bit more time for the new edge to follow.

**Comment by cx20** [comment] 2019-11-23 14:44
Chrome Canary 80.0.3975.0 seems to have improved the WebGPU error. Now, Babylon.js WebGPU sample can be displayed with ThinkPad X260 built-in GPU.
With Edge Canary 80.0.3971.0, WebGPU still has an error, so it seems to need to wait a little longer.

**Comment by sebavan** [comment] 2019-11-23 15:42
Yep it is related to my previous message and would probably need a week or two to go in :-) but good to know it works on more devices.

**Comment by cx20** [comment] 2019-11-29 13:20
I recently got a new environment (MacBookAir), so I tried WebGPU with Babylon.js.
However, Babylon.js PlayGround GPU does not seem to work on MacBookAir + BootCamp + Windows 10 + Chrome Canary.

![image](https://user-images.githubusercontent.com/1833979/69868573-6b999d80-12ed-11ea-9b93-f579e4232ca9.png)

Please let me know if there is a solution. 
I wanted to disable "Skia API for OOP-D compositing", but it seems that the flag does not exist in the latest version of Chrome Canary.

**Comment by sebavan** [comment] 2019-11-29 13:25
No idea as here it is pretty specific :-( might be worth reaching out to the chromium team for those as it might be driver related ?

for us, we are trying to stay as much as we can in sync with the first release being Chrome on Mac. Then we are pretty confident it should work a couple of days later on Chrome Windows and finally on  Edge for windows a bit after that.

**Comment by cx20** [comment] 2019-11-29 13:31
@sebavan Thank you for the advice. I would like to report it in a Chrome Canary bug report.

**Comment by kutomer** [comment] 2020-03-08 11:19
Hey, @sebavan any news on this?

**Comment by sebavan** [comment] 2020-03-08 11:37
Yup, We are currently for more stabilization of WGSL which sounds to be the chosen language for shaders in WebGPU. As the language is just as its premises so far we prefer to focus on other prios for the time being. I will meet with the Google team soon-ish to see when we are doing the change but I am hoping to start back on it this summer once we ensure it is all good to go.

**Comment by cx20** [comment] 2020-03-23 18:38
Currently, [Babylon.js Playground WebGPU](https://playground.babylonjs.com/indexWebGPU.html) does not seem to work with the latest version of Chrome Canary.

|browser      |version           |[WebGPU Samples](https://austineng.github.io/webgpu-samples/#rotatingCube)|[Babylon.js Playground WebGPU](https://playground.babylonjs.com/indexWebGPU.html)   |
|-------------|------------------|:------------------------------------------------------------------------:|:----------------------------------------------------------------------------------:|
|Chrome Canary|Chrome/83.0.4093.0|:x:                                                                       |:x:                                                                                 |
|Edge Canary  |Chrome/82.0.4083.0|:white_check_mark:                                                        |:white_check_mark:                                                                  |

Perhaps it will work by referencing the latest `glslang`.

**Comment by sebavan** [comment] 2020-03-23 19:45
As the shader language will change, I won t update glslang for now, but I ll check if it is only a simple change tomorrow.

**Comment by sebavan** [comment] 2020-03-23 20:44
@cx20 Did you try on Mac or Windows ??? thanks

**Comment by sebavan** [comment] 2020-03-23 22:11
Actually it looks like it might be an issue with the latest CDN changes. the wasm file looks served with the wrong mime type: 

![image](https://user-images.githubusercontent.com/16655165/77367985-948de480-6d5b-11ea-93a0-381cfacd23c5.png)

@RaananW could you try from https://playground.babylonjs.com/indexWebGPU.html in chrome Canary with the Webgpu flag turned on ?

**Comment by sebavan** [comment] 2020-03-23 22:22
Actually, it looks like it does not run on Windows anymore, did you try other demos @cx20 on windows ? I am not getting any of them working atm.

**Comment by sebavan** [comment] 2020-03-23 22:46
I created the according Chromium ticket to double check: https://bugs.chromium.org/p/chromium/issues/detail?id=1064110

**Comment by cx20** [comment] 2020-03-23 22:47
@sebavan I have confirmed that the problem occurs on both Windows and MacOS Chrome Canary.
I had the same problem in the following repository samples, but updating glslang solved the problem.
https://github.com/cx20/webgpu-test

Related: https://github.com/austinEng/webgpu-samples/issues/33

**Comment by sebavan** [comment] 2020-03-23 22:53
Ok so I ll try to fix it at least for MacOS as on Windows for me, I can not make it run at the moment. (none of your samples.)

**Comment by sebavan** [comment] 2020-03-24 00:07
Ok so I commited the glslang fix but it is soon to be deployed.

@RaananW , the file https://preview.babylonjs.com/glslang/glslang.js is not the same as https://github.com/BabylonJS/Babylon.js/blob/preview/dist/preview%20release/glslang/glslang.js

I can not think of any good reason aside of the deploy process ? any idea ? I can not debug as it seems it is not yes from the common subscription... I guess :-) Would really appreciate if you can have a look.

**Comment by sebavan** [comment] 2020-03-24 00:24
@RaananW I forced a manual purge and all good... no idea, do not ask :-) ... So @cx20 it should be all good. I might nevertheless fail on windows like other webgpu projects related to the previous chromium ticker: https://bugs.chromium.org/p/chromium/issues/detail?id=1064110

**Comment by cx20** [comment] 2020-03-24 11:41
@sebavan Thanks. I have confirmed that [Babylon.js Playground WebGPU](https://playground.babylonjs.com/indexWebGPU.html) can be displayed again on both Windows and Mac Chrome Canary.

**Comment by cx20** [comment] 2020-04-29 14:47
WebGPU has come to work recently with Firefox Nightly. 
However, [Babylon.js WebGPU Playground](https://playground.babylonjs.com/indexWebGPU.html) does not display with an error. 
It seems that `setSubData` cannot be used with the latest WebGPU API.
Even Chrome Canary has deprecated `setSubData`, so I hope you can migrate to the latest WebGPU API.

**Comment by deltakosh** [comment] 2020-04-29 14:48
cc @sebavan

**Comment by sebavan** [comment] 2020-04-29 15:19
I will migrate next week as there is a quite large refactor of the APIs in process. The setSubData has already been fixed but not deployed due to the other required changes.

The main issue is the ecosystem fragmentation and I do not know at what extends testing on all the platforms is fully relevant as they are all evolving separately.

I have great hopes that after the shader language changes, things would be less fragmented.

**Comment by sebavan** [comment] 2020-05-12 23:59
Just migrated and merge with master, it is uptospec so there might be issues with not uptodate browsers ;-) but at least it has been updated.

**Comment by cx20** [comment] 2020-05-13 14:10
@sebavan Thank you for updating. I have confirmed that the warning has been resolved in Chrome Canary.
BTW, when displaying [Babylon.js WebGPU Playground](https://playground.babylonjs.com/indexWebGPU.html) in Firefox Nightly, it seems that an error appears in the part that is not related to WebGPU.
```
babylonWebGpu.max.js:1:1
Uncaught SyntaxError: invalid regexp group 
```

**Comment by sebavan** [comment] 2020-05-14 01:41
@cx20, so no more issue on this side but firefox now just crashes on Windows, you might ping them as it sounds on their side :-(

**Comment by cx20** [comment] 2020-05-14 14:10
@sebavan Thank you for fixing regexp. I have made a separate bug report regarding the crash.
https://bugzilla.mozilla.org/show_bug.cgi?id=1637972

**Comment by 0x00002152** [comment] 2020-06-03 16:47
maybe fun fact for anybody who is interested, firefox nightly with webgpu works on linux, although when I try any of the babylon.js links the tab crashes. Sort of trying to figure out if I can get more verbosity out of firefox (running from command line) not really sure how to though.

**Comment by sebavan** [comment] 2020-06-03 17:32
@0x00002152 looks like it has been ack as a bug on the firefox side: https://bugzilla.mozilla.org/show_bug.cgi?id=1637972

**Comment by cx20** [comment] 2020-09-05 23:12
Currently, [Playground](https://playground.babylonjs.com/indexWebGPU.html) is experiencing an error due to a change in the WebGPU API specification.
https://playground.babylonjs.com/indexWebGPU.html

```javascript
mainWebGPU.js:1 
TypeError: this._device.createBufferMapped is not a function
    at t._createBuffer (babylonWebGpu.max.js:1)
    at t.createUniformBuffer (babylonWebGpu.max.js:1)
```

The versions of browsers I have tried are as follows
Browser : Chrome Canary `87.0.4255.1`

The recent changes to the WebGPU API may be helpful in the following articles

PSA for Chromium / Dawn WebGPU API updates 2020-07-28
https://hackmd.io/szV68rOVQ56GYzPJMBko8A

**Comment by Popov72** [comment] 2020-09-06 08:19
It has already been corrected but the code is not deployed yet.

**Comment by sebavan** [comment] 2020-09-06 13:26
We actually wont be redeploying the WebGPU PG before the merge to master planned to happen right after our 4.2 release and then full steam on WebGPU :-)

**Comment by cx20** [comment] 2020-09-06 14:51
@Popov72 @sebavan Thanks for letting me know. I'm looking forward to 4.2 being released.

**Comment by stefansundin** [comment] 2021-11-12 21:39
Hello. I am testing WebGPU using electron 15 and the version of Babylon.js that is served from preview.babylonjs.com, and there's a small problem with the content-type for `glslang.wasm`. It is printing a warning/error in the console but I am unsure if there's any actual problems.

> glslang.js:36 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

```
$ curl -I -s https://cdn.babylonjs.com/glslang/glslang.wasm | grep content-type
content-type: application/wasm
$ curl -I -s https://preview.babylonjs.com/glslang/glslang.wasm | grep content-type
content-type: application/octet-stream
```

**Comment by Popov72** [comment] 2021-11-12 23:12
No it's ok even with this warning (I get it also).

I will see if we can change the mime type of the preview CDN.

**Comment by RaananW** [comment] 2021-11-15 11:05
The mime type was changed to `application/wasm`

**Comment by thomlucc** [comment] 2022-01-11 16:36
Delivered by @Popov72. Thanks!!!!

**Closed by thomlucc** 2022-01-11 16:36 UTC
Labels: enhancement, rendering engine, in progress, WebGPU
